export type HocLieuFileType =
  | "PDF"
  | "PPTX"
  | "VIDEO"
  | "AUDIO"
  | "HTML5"
  | "LINK"
  | "QUIZ"
  | "ZIP"
  | "DOCX"
  | "XLSX"
  | "IMAGE";

export type HocLieuLaunchMode =
  | "pdf_reader"
  | "ebook_reader"
  | "google_slide_embed"
  | "custom_slide_viewer"
  | "slide_image_proxy"
  | "video_player"
  | "audio_player"
  | "html5_embed"
  | "quiz_runtime"
  | "download_only"
  | "external";

export type HocLieuPriceType = "free" | "paid" | "licensed";
export type HocLieuAccessState = "open" | "login_required" | "license_required" | "unavailable";

export type HocLieuGrade = {
  id: string;
  label: string;
};

export type HocLieuSubject = {
  id: string;
  label: string;
  gradeIds?: string[];
};

export type HocLieuCategory = {
  id: string;
  label: string;
  parentId?: string;
  icon: "book" | "document" | "stem" | "certificate" | "computer" | "smart";
};

export type HocLieuResourceSection = {
  id: string;
  title: string;
  subtitle?: string;
  gradeId?: string;
  subjectId: string;
  categoryId: string;
  resources: HocLieuResource[];
};

export type HocLieuViewerUnit = {
  id: string;
  title: string;
  children?: Array<{ id: string; title: string; duration?: string }>;
};

export type HocLieuViewerSlide = {
  id: string;
  index: number;
  title?: string;
  imageUrl: string;
  thumbnailUrl?: string;
};

export type HocLieuResource = {
  id: string;
  slug: string;
  title: string;
  subtitle?: string;
  gradeId?: string;
  subjectId: string;
  categoryId: string;
  sectionId: string;
  topicId?: string;
  bookSeriesId?: string;
  resourceType:
    | "ebook"
    | "pdf"
    | "audio"
    | "lesson_plan"
    | "slide"
    | "teacher_book"
    | "test_bank"
    | "video"
    | "lecture_bank"
    | "image_bank"
    | "quiz"
    | "download_package"
    | "interactive"
    | "external_link";
  fileType: HocLieuFileType;
  formatBadge: string;
  launchMode: HocLieuLaunchMode;
  thumbnailUrl?: string;
  thumbnailLabel: string;
  thumbnailSubLabel?: string;
  thumbnailTheme: "blue" | "green" | "orange" | "purple" | "teal" | "rose" | "yellow" | "slate";
  priceType: HocLieuPriceType;
  accessState: HocLieuAccessState;
  isDownloadable: boolean;
  sortOrder: number;
  viewer: {
    assetId?: string;
    resourceId?: string;
    title: string;
    description: string;
    pageCount?: number;
    duration?: string;
    embedUrl?: string;
    secureEmbedUrl?: string;
    launchUrl?: string;
    presentationTitle?: string;
    slides?: HocLieuViewerSlide[];
    units?: HocLieuViewerUnit[];
  };
};

export const HOCLIEU_GRADES: HocLieuGrade[] = [
  { id: "mam-non", label: "Máº§m non" },
  ...Array.from({ length: 12 }, (_, index) => {
    const value = String(index + 1);
    return { id: value, label: value };
  }),
];

export const HOCLIEU_SUBJECTS: HocLieuSubject[] = [
  { id: "all", label: "Táº¥t cáº£" },
  { id: "toan", label: "ToÃ¡n" },
  { id: "tieng-viet", label: "Tiáº¿ng Viá»‡t" },
  { id: "tu-nhien-xa-hoi", label: "Tá»± nhiÃªn vÃ  XÃ£ há»™i", gradeIds: ["1", "2", "3"] },
  { id: "ngu-van", label: "Ngá»¯ vÄƒn" },
  { id: "tieng-anh", label: "Tiáº¿ng Anh" },
  { id: "khoa-hoc-tu-nhien", label: "Khoa há»c tá»± nhiÃªn" },
  { id: "lich-su-dia-li", label: "Lá»‹ch sá»­ vÃ  Äá»‹a lÃ­" },
  { id: "giao-duc-stem", label: "GiÃ¡o dá»¥c STEM" },
  { id: "giao-duc-ki-nang-cong-dan-so", label: "GiÃ¡o dá»¥c KÄ© nÄƒng CÃ´ng dÃ¢n sá»‘" },
  { id: "tin-hoc", label: "Tin há»c" },
  { id: "ic3", label: "IC3" },
  { id: "mos", label: "MOS" },
];

export const HOCLIEU_CATEGORIES: HocLieuCategory[] = [
  { id: "nhat-ki-ngay-he-vui", label: "Nháº­t kÃ­ ngÃ y hÃ¨ vui", icon: "document" },
  { id: "sgk-tieng-anh", label: "Há»c liá»‡u SGK Tiáº¿ng Anh", icon: "book" },
  { id: "sach-mem-2", label: "SÃ¡ch Má»m 2.0", parentId: "sgk-tieng-anh", icon: "document" },
  { id: "hop-phan-bo-tro", label: "Há»£p pháº§n bá»• trá»£", parentId: "sgk-tieng-anh", icon: "document" },
  { id: "tieng-anh-tang-cuong", label: "Tiáº¿ng Anh TÄƒng CÆ°á»ng", icon: "book" },
  { id: "global-maths", label: "Global Maths", parentId: "tieng-anh-tang-cuong", icon: "document" },
  { id: "global-science", label: "Global Science", parentId: "tieng-anh-tang-cuong", icon: "document" },
  { id: "hoc-lieu-thong-minh", label: "Há»c liá»‡u ThÃ´ng minh", icon: "smart" },
  { id: "ket-noi-tri-thuc", label: "Káº¿t ná»‘i tri thá»©c vá»›i cuá»™c sá»‘ng", parentId: "hoc-lieu-thong-minh", icon: "document" },
  { id: "chan-troi-sang-tao", label: "ChÃ¢n trá»i sÃ¡ng táº¡o", parentId: "hoc-lieu-thong-minh", icon: "document" },
  { id: "cung-hoc-phat-trien", label: "CÃ¹ng há»c Ä‘á»ƒ phÃ¡t triá»ƒn nÄƒng lá»±c", parentId: "hoc-lieu-thong-minh", icon: "document" },
  { id: "theo-sgk-khac", label: "Theo SGK khÃ¡c", parentId: "hoc-lieu-thong-minh", icon: "document" },
  { id: "hoc-lieu-giao-duc-khac", label: "Há»c liá»‡u GiÃ¡o dá»¥c khÃ¡c", icon: "stem" },
  { id: "giao-duc-stem", label: "Há»c liá»‡u GiÃ¡o dá»¥c STEM", parentId: "hoc-lieu-giao-duc-khac", icon: "stem" },
  { id: "hoc-lieu-sach-tham-khao", label: "Há»c liá»‡u SÃ¡ch tham kháº£o", parentId: "hoc-lieu-giao-duc-khac", icon: "document" },
  { id: "hoc-lieu-hanh-trang-cong-dan-so", label: "Há»c liá»‡u HÃ nh trang cÃ´ng dÃ¢n sá»‘", parentId: "hoc-lieu-giao-duc-khac", icon: "document" },
  { id: "hoc-lieu-tin-hoc", label: "Há»c liá»‡u Tin há»c", icon: "computer" },
  { id: "tin-hoc-pho-thong", label: "Tin há»c phá»• thÃ´ng", parentId: "hoc-lieu-tin-hoc", icon: "computer" },
  { id: "scratch-python", label: "Scratch & Python", parentId: "hoc-lieu-tin-hoc", icon: "computer" },
  { id: "chung-chi-tin-hoc", label: "Chá»©ng chá»‰ Tin há»c", icon: "certificate" },
  { id: "ic3-digital-literacy", label: "IC3 Digital Literacy", parentId: "chung-chi-tin-hoc", icon: "certificate" },
  { id: "mos", label: "MOS", parentId: "chung-chi-tin-hoc", icon: "certificate" },
];

const MOCK_GOOGLE_PDF_EMBED_URL = "/mock/hoclieu/global-success-preview.b64";
const MOCK_SLIDES_EMBED_URL = "/mock/hoclieu/slide-preview.html";

const commonLectureUnits: HocLieuViewerUnit[] = [
  {
    id: "unit-1",
    title: "Unit 1: My new school",
    children: [
      { id: "lesson-1", title: "Unit 1_Lesson 1_Period 1", duration: "35 phÃºt" },
      { id: "lesson-2", title: "Unit 1_Lesson 2_Period 2", duration: "35 phÃºt" },
      { id: "lesson-3", title: "Unit 1_Lesson 3_Period 3", duration: "35 phÃºt" },
    ],
  },
  { id: "unit-2", title: "Unit 2: My house" },
  { id: "unit-3", title: "Unit 3: My friends" },
  { id: "unit-4", title: "Unit 4: My neighbourhood" },
  { id: "unit-5", title: "Unit 5: Natural wonders of Viet Nam" },
  { id: "unit-6", title: "Unit 6: Our Tet holiday" },
  { id: "unit-7", title: "Unit 7: Television" },
  { id: "unit-8", title: "Unit 8: Sports and Games" },
  { id: "unit-9", title: "Unit 9: Cities of the World" },
];

export const HOCLIEU_LIBRARY_SECTIONS: HocLieuResourceSection[] = [
  {
    id: "nhat-ki-ngay-he-vui",
    title: "NHáº¬T KÃ NGÃ€Y HÃˆ VUI",
    subtitle: "Há»c liá»‡u hÃ¨ cho há»c sinh lá»›p 1, má»Ÿ nhanh tá»« kho há»c liá»‡u.",
    gradeId: "1",
    subjectId: "all",
    categoryId: "nhat-ki-ngay-he-vui",
    resources: [
      {
        id: "nhat-ki-ngay-he-vui-lop-1",
        slug: "nhat-ki-ngay-he-vui-lop-1",
        title: "Nháº­t kÃ­ ngÃ y hÃ¨ vui Lá»›p 1",
        subtitle: "Bá»™ há»c liá»‡u tÃ­ch há»£p ToÃ¡n, Tiáº¿ng Viá»‡t, Tiáº¿ng Anh",
        gradeId: "1",
        subjectId: "all",
        categoryId: "nhat-ki-ngay-he-vui",
        sectionId: "nhat-ki-ngay-he-vui",
        resourceType: "interactive",
        fileType: "HTML5",
        formatBadge: "HTML5",
        launchMode: "html5_embed",
        thumbnailLabel: "Nháº­t kÃ­ ngÃ y hÃ¨ vui",
        thumbnailSubLabel: "Lá»›p 1",
        thumbnailTheme: "blue",
        priceType: "licensed",
        accessState: "license_required",
        isDownloadable: false,
        sortOrder: 1,
        viewer: {
          title: "Nháº­t kÃ­ ngÃ y hÃ¨ vui Lá»›p 1",
          description: "Há»c liá»‡u HTML5 mÃ´ phá»ng thao tÃ¡c kÃ­ch hoáº¡t sá»­ dá»¥ng vÃ  má»Ÿ bÃ i há»c.",
          embedUrl: MOCK_SLIDES_EMBED_URL,
          units: [
            { id: "nk-bai-1", title: "Tuáº§n 1: Khá»Ÿi Ä‘á»™ng mÃ¹a hÃ¨" },
            { id: "nk-bai-2", title: "Tuáº§n 2: Ã”n táº­p ToÃ¡n vÃ  Tiáº¿ng Viá»‡t" },
            { id: "nk-bai-3", title: "Tuáº§n 3: Em ká»ƒ chuyá»‡n ngÃ y hÃ¨" },
          ],
        },
      },
    ],
  },
  {
    id: "sach-mem-2-lop-1",
    title: "Há»ŒC LIá»†U SGK TIáº¾NG ANH",
    subtitle: "SÃ¡ch Má»m 2.0",
    gradeId: "1",
    subjectId: "tieng-anh",
    categoryId: "sach-mem-2",
    resources: [
      {
        id: "global-success-1-student-book",
        slug: "tieng-anh-1-global-success-sach-hoc-sinh",
        title: "Tiáº¿ng Anh 1 - Global Success",
        subtitle: "SÃ¡ch há»c sinh",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "sach-mem-2",
        sectionId: "sach-mem-2-lop-1",
        resourceType: "ebook",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "ebook_reader",
        thumbnailLabel: "Global Success",
        thumbnailSubLabel: "PhiÃªn báº£n GV",
        thumbnailTheme: "green",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 1,
        viewer: {
          title: "Tiáº¿ng Anh 1 - Global Success",
          description: "PDF xem trá»±c tiáº¿p báº±ng Google Drive preview trong modal.",
          pageCount: 96,
          embedUrl: MOCK_GOOGLE_PDF_EMBED_URL,
        },
      },
      {
        id: "global-success-1-workbook",
        slug: "tieng-anh-1-global-success-sach-bai-tap",
        title: "Tiáº¿ng Anh 1 - Global Success",
        subtitle: "SÃ¡ch bÃ i táº­p",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "sach-mem-2",
        sectionId: "sach-mem-2-lop-1",
        resourceType: "pdf",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "Workbook 1",
        thumbnailSubLabel: "PhiÃªn báº£n GV",
        thumbnailTheme: "yellow",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 2,
        viewer: {
          title: "Tiáº¿ng Anh 1 - Global Success - SÃ¡ch bÃ i táº­p",
          description: "PDF xem trá»±c tiáº¿p báº±ng Google Drive preview trong modal.",
          pageCount: 72,
          embedUrl: MOCK_GOOGLE_PDF_EMBED_URL,
        },
      },
    ],
  },
  {
    id: "hop-phan-bo-tro-lop-1",
    title: "Há»£p pháº§n bá»• trá»£",
    gradeId: "1",
    subjectId: "tieng-anh",
    categoryId: "hop-phan-bo-tro",
    resources: [
      {
        id: "global-success-1-audio",
        slug: "global-success-1-audio",
        title: "Audio",
        subtitle: "Tiáº¿ng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "audio",
        fileType: "AUDIO",
        formatBadge: "AUDIO",
        launchMode: "audio_player",
        thumbnailLabel: "Audio",
        thumbnailTheme: "teal",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 1,
        viewer: { title: "Audio - Tiáº¿ng Anh 1", description: "Danh sÃ¡ch audio theo unit.", duration: "01:12:00" },
      },
      {
        id: "global-success-1-lesson-plan",
        slug: "global-success-1-ke-hoach-day-hoc",
        title: "Káº¿ hoáº¡ch dáº¡y há»c",
        subtitle: "Tiáº¿ng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "lesson_plan",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "Káº¿ hoáº¡ch dáº¡y há»c",
        thumbnailTheme: "orange",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 2,
        viewer: { title: "Káº¿ hoáº¡ch dáº¡y há»c - Tiáº¿ng Anh 1", description: "PDF káº¿ hoáº¡ch dáº¡y há»c.", pageCount: 32 },
      },
      {
        id: "global-success-1-slide",
        slug: "global-success-1-bai-giang-dien-tu",
        title: "BÃ i giáº£ng Ä‘iá»‡n tá»­",
        subtitle: "Tiáº¿ng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "slide",
        fileType: "PPTX",
        formatBadge: "PPTX",
        launchMode: "google_slide_embed",
        thumbnailLabel: "BÃ i giáº£ng Ä‘iá»‡n tá»­",
        thumbnailTheme: "orange",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 3,
        viewer: { title: "BÃ i giáº£ng Ä‘iá»‡n tá»­ - Tiáº¿ng Anh 1", description: "PPTX xem trá»±c tiáº¿p qua Google Slides embed.", embedUrl: MOCK_SLIDES_EMBED_URL, units: commonLectureUnits },
      },
      {
        id: "global-success-1-demo-lesson",
        slug: "global-success-1-giao-an-minh-hoa",
        title: "GiÃ¡o Ã¡n minh há»a",
        subtitle: "Tiáº¿ng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "lesson_plan",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "GiÃ¡o Ã¡n minh há»a",
        thumbnailTheme: "rose",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 4,
        viewer: { title: "GiÃ¡o Ã¡n minh há»a", description: "PDF giÃ¡o Ã¡n minh há»a.", pageCount: 18 },
      },
      {
        id: "global-success-1-flashcards",
        slug: "global-success-1-the-tu",
        title: "Tháº» tá»«",
        subtitle: "Tiáº¿ng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "image_bank",
        fileType: "IMAGE",
        formatBadge: "IMAGE",
        launchMode: "external",
        thumbnailLabel: "Tháº» tá»«",
        thumbnailTheme: "teal",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 5,
        viewer: { title: "Tháº» tá»«", description: "Bá»™ tháº» tá»« dÃ¹ng trÃªn lá»›p." },
      },
      {
        id: "global-success-1-situation-cards",
        slug: "global-success-1-tranh-tinh-huong",
        title: "Tranh tÃ¬nh huá»‘ng",
        subtitle: "Tiáº¿ng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "image_bank",
        fileType: "IMAGE",
        formatBadge: "IMAGE",
        launchMode: "external",
        thumbnailLabel: "Tranh tÃ¬nh huá»‘ng",
        thumbnailTheme: "purple",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 6,
        viewer: { title: "Tranh tÃ¬nh huá»‘ng", description: "Bá»™ tranh tÃ¬nh huá»‘ng theo bÃ i há»c." },
      },
      {
        id: "global-success-1-puppets",
        slug: "global-success-1-bo-quan-roi",
        title: "Bá»™ quÃ¢n rá»‘i",
        subtitle: "Tiáº¿ng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "image_bank",
        fileType: "IMAGE",
        formatBadge: "IMAGE",
        launchMode: "external",
        thumbnailLabel: "Bá»™ quÃ¢n rá»‘i",
        thumbnailTheme: "teal",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 7,
        viewer: { title: "Bá»™ quÃ¢n rá»‘i", description: "TÃ i nguyÃªn quÃ¢n rá»‘i lá»›p há»c." },
      },
      {
        id: "global-success-1-sample-test",
        slug: "global-success-1-de-kiem-tra-minh-hoa",
        title: "Äá» kiá»ƒm tra minh há»a",
        subtitle: "Tiáº¿ng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "test_bank",
        fileType: "QUIZ",
        formatBadge: "QUIZ",
        launchMode: "quiz_runtime",
        thumbnailLabel: "Äá» kiá»ƒm tra minh há»a",
        thumbnailTheme: "green",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 8,
        viewer: { title: "Äá» kiá»ƒm tra minh há»a", description: "Bá»™ Ä‘á» kiá»ƒm tra minh há»a." },
      },
      {
        id: "global-success-1-test-bank",
        slug: "global-success-1-ngan-hang-de-kiem-tra",
        title: "NgÃ¢n hÃ ng Ä‘á» kiá»ƒm tra",
        subtitle: "Tiáº¿ng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "test_bank",
        fileType: "QUIZ",
        formatBadge: "QUIZ",
        launchMode: "quiz_runtime",
        thumbnailLabel: "NgÃ¢n hÃ ng Ä‘á» kiá»ƒm tra",
        thumbnailTheme: "green",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 9,
        viewer: { title: "NgÃ¢n hÃ ng Ä‘á» kiá»ƒm tra", description: "NgÃ¢n hÃ ng cÃ¢u há»i kiá»ƒm tra." },
      },
      {
        id: "global-success-1-demo-video",
        slug: "global-success-1-video-tiet-day-minh-hoa",
        title: "Video tiáº¿t dáº¡y minh há»a",
        subtitle: "Tiáº¿ng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "video",
        fileType: "VIDEO",
        formatBadge: "VIDEO",
        launchMode: "video_player",
        thumbnailLabel: "Video tiáº¿t dáº¡y minh há»a",
        thumbnailTheme: "green",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 10,
        viewer: { title: "Video tiáº¿t dáº¡y minh há»a", description: "Video player tá»‘i giáº£n.", duration: "15:28" },
      },
      {
        id: "global-success-1-pronunciation-video",
        slug: "global-success-1-video-huong-dan-phat-am",
        title: "Video hÆ°á»›ng dáº«n phÃ¡t Ã¢m",
        subtitle: "Tiáº¿ng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "video",
        fileType: "VIDEO",
        formatBadge: "VIDEO",
        launchMode: "video_player",
        thumbnailLabel: "Video hÆ°á»›ng dáº«n phÃ¡t Ã¢m",
        thumbnailTheme: "purple",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 11,
        viewer: { title: "Video hÆ°á»›ng dáº«n phÃ¡t Ã¢m", description: "Video hÆ°á»›ng dáº«n phÃ¡t Ã¢m.", duration: "12:02" },
      },
      {
        id: "global-success-1-cartoon",
        slug: "global-success-1-video-hoat-hinh",
        title: "Video hoáº¡t hÃ¬nh",
        subtitle: "Tiáº¿ng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "video",
        fileType: "VIDEO",
        formatBadge: "VIDEO",
        launchMode: "video_player",
        thumbnailLabel: "Video hoáº¡t hÃ¬nh",
        thumbnailTheme: "blue",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 12,
        viewer: { title: "Video hoáº¡t hÃ¬nh", description: "Video hoáº¡t hÃ¬nh theo unit.", duration: "10:04" },
      },
      {
        id: "global-success-1-teacher-book",
        slug: "global-success-1-sach-giao-vien",
        title: "SÃ¡ch giÃ¡o viÃªn",
        subtitle: "Tiáº¿ng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "teacher_book",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "SÃ¡ch giÃ¡o viÃªn",
        thumbnailTheme: "rose",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 13,
        viewer: { title: "SÃ¡ch giÃ¡o viÃªn - Tiáº¿ng Anh 1", description: "PDF sÃ¡ch giÃ¡o viÃªn.", pageCount: 156 },
      },
      {
        id: "global-success-1-vocabulary",
        slug: "global-success-1-tong-hop-tu-vung",
        title: "Tá»•ng há»£p tá»« vá»±ng",
        subtitle: "Tiáº¿ng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "pdf",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "Tá»•ng há»£p tá»« vá»±ng",
        thumbnailTheme: "yellow",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 14,
        viewer: { title: "Tá»•ng há»£p tá»« vá»±ng", description: "Báº£ng tá»•ng há»£p tá»« vá»±ng.", pageCount: 24 },
      },
      {
        id: "global-success-1-expanded-pack",
        slug: "global-success-1-tai-nguyen-mo-rong",
        title: "TÃ i nguyÃªn má»Ÿ rá»™ng",
        subtitle: "Tiáº¿ng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "download_package",
        fileType: "ZIP",
        formatBadge: "ZIP",
        launchMode: "download_only",
        thumbnailLabel: "TÃ i nguyÃªn má»Ÿ rá»™ng",
        thumbnailTheme: "rose",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 15,
        viewer: { title: "TÃ i nguyÃªn má»Ÿ rá»™ng", description: "GÃ³i tÃ i nguyÃªn má»Ÿ rá»™ng táº£i xuá»‘ng." },
      },
    ],
  },
  {
    id: "sach-mem-2",
    title: "SÃ¡ch Má»m 2.0",
    subtitle: "Bá»™ sÃ¡ch há»c sinh vÃ  sÃ¡ch bÃ i táº­p theo lá»›p.",
    gradeId: "7",
    subjectId: "tieng-anh",
    categoryId: "sach-mem-2",
    resources: [
      {
        id: "global-success-7-student-book",
        slug: "tieng-anh-7-global-success-sach-hoc-sinh",
        title: "Tiáº¿ng Anh 7 - Global Success",
        subtitle: "SÃ¡ch há»c sinh",
        gradeId: "7",
        subjectId: "tieng-anh",
        categoryId: "sach-mem-2",
        sectionId: "sach-mem-2",
        resourceType: "ebook",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "ebook_reader",
        thumbnailLabel: "Global Success",
        thumbnailSubLabel: "PhiÃªn báº£n GV",
        thumbnailTheme: "blue",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 1,
        viewer: {
          title: "Tiáº¿ng Anh 7 - Global Success",
          description: "PDF xem trá»±c tiáº¿p báº±ng Google Drive preview trong modal.",
          pageCount: 128,
          embedUrl: MOCK_GOOGLE_PDF_EMBED_URL,
        },
      },
      {
        id: "global-success-7-workbook",
        slug: "tieng-anh-7-global-success-sach-bai-tap",
        title: "Tiáº¿ng Anh 7 - Global Success",
        subtitle: "SÃ¡ch bÃ i táº­p",
        gradeId: "7",
        subjectId: "tieng-anh",
        categoryId: "sach-mem-2",
        sectionId: "sach-mem-2",
        resourceType: "pdf",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "Workbook 7",
        thumbnailSubLabel: "PhiÃªn báº£n GV",
        thumbnailTheme: "yellow",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 2,
        viewer: {
          title: "Tiáº¿ng Anh 7 - Global Success - SÃ¡ch bÃ i táº­p",
          description: "PDF xem trá»±c tiáº¿p báº±ng Google Drive preview trong modal.",
          pageCount: 96,
          embedUrl: MOCK_GOOGLE_PDF_EMBED_URL,
        },
      },
    ],
  },
  {
    id: "hop-phan-bo-tro",
    title: "Há»£p pháº§n bá»• trá»£",
    subtitle: "CÃ¡c tÃ i nguyÃªn Ä‘i kÃ¨m bÃ i há»c vÃ  bá»™ sÃ¡ch.",
    gradeId: "7",
    subjectId: "tieng-anh",
    categoryId: "hop-phan-bo-tro",
    resources: [
      {
        id: "global-success-7-audio",
        slug: "global-success-7-audio",
        title: "Audio",
        subtitle: "Tiáº¿ng Anh 7 - Global Success",
        gradeId: "7",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro",
        resourceType: "audio",
        fileType: "AUDIO",
        formatBadge: "AUDIO",
        launchMode: "audio_player",
        thumbnailLabel: "Audio",
        thumbnailTheme: "green",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 1,
        viewer: {
          title: "Audio - Tiáº¿ng Anh 7",
          description: "Danh sÃ¡ch audio theo unit, dÃ¹ng player compact.",
          duration: "02:18:00",
        },
      },
      {
        id: "global-success-7-lesson-plan",
        slug: "global-success-7-ke-hoach-day-hoc",
        title: "Káº¿ hoáº¡ch dáº¡y há»c",
        subtitle: "Tiáº¿ng Anh 7 - Global Success",
        gradeId: "7",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro",
        resourceType: "lesson_plan",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "Káº¿ hoáº¡ch dáº¡y há»c",
        thumbnailTheme: "blue",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 2,
        viewer: {
          title: "Káº¿ hoáº¡ch dáº¡y há»c",
          description: "PDF xem trá»±c tiáº¿p báº±ng Google Drive preview trong modal.",
          pageCount: 11,
          embedUrl: MOCK_GOOGLE_PDF_EMBED_URL,
        },
      },
      {
        id: "global-success-7-slide",
        slug: "global-success-7-bai-giang-dien-tu",
        title: "BÃ i giáº£ng Ä‘iá»‡n tá»­",
        subtitle: "Tiáº¿ng Anh 7 - Global Success",
        gradeId: "7",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro",
        resourceType: "slide",
        fileType: "PPTX",
        formatBadge: "PPTX",
        launchMode: "google_slide_embed",
        thumbnailLabel: "BÃ i giáº£ng Ä‘iá»‡n tá»­",
        thumbnailTheme: "orange",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 3,
        viewer: {
          title: "BÃ i giáº£ng Ä‘iá»‡n tá»­",
          description: "PPTX xem trá»±c tiáº¿p qua Google Slides embed. UI khÃ´ng hiá»ƒn thá»‹ link gá»‘c.",
          embedUrl: MOCK_SLIDES_EMBED_URL,
          presentationTitle: "Lesson 1 - GETTING STARTED",
          units: commonLectureUnits,
        },
      },
      {
        id: "global-success-7-test-bank",
        slug: "global-success-7-ngan-hang-de-kiem-tra",
        title: "NgÃ¢n hÃ ng Ä‘á» kiá»ƒm tra",
        subtitle: "Tiáº¿ng Anh 7 - Global Success",
        gradeId: "7",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro",
        resourceType: "test_bank",
        fileType: "QUIZ",
        formatBadge: "QUIZ",
        launchMode: "quiz_runtime",
        thumbnailLabel: "NgÃ¢n hÃ ng Ä‘á»",
        thumbnailTheme: "purple",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 4,
        viewer: {
          title: "NgÃ¢n hÃ ng Ä‘á» kiá»ƒm tra",
          description: "Äiá»u hÆ°á»›ng sang quiz/runtime khi BE cung cáº¥p package tháº­t.",
        },
      },
      {
        id: "global-success-7-video",
        slug: "global-success-7-video-tiet-day-minh-hoa",
        title: "Video tiáº¿t dáº¡y minh há»a",
        subtitle: "Tiáº¿ng Anh 7 - Global Success",
        gradeId: "7",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro",
        resourceType: "video",
        fileType: "VIDEO",
        formatBadge: "VIDEO",
        launchMode: "video_player",
        thumbnailLabel: "Video tiáº¿t dáº¡y",
        thumbnailTheme: "rose",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 5,
        viewer: {
          title: "Video tiáº¿t dáº¡y minh há»a",
          description: "Video player tá»‘i giáº£n, khÃ´ng autoplay.",
          duration: "18:42",
        },
      },
      {
        id: "global-success-7-teacher-pack",
        slug: "global-success-7-file-thuc-hanh",
        title: "File thá»±c hÃ nh lá»›p há»c",
        subtitle: "Tiáº¿ng Anh 7 - Global Success",
        gradeId: "7",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro",
        resourceType: "download_package",
        fileType: "ZIP",
        formatBadge: "ZIP",
        launchMode: "download_only",
        thumbnailLabel: "Practice Pack",
        thumbnailTheme: "slate",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 6,
        viewer: {
          title: "File thá»±c hÃ nh lá»›p há»c",
          description: "GÃ³i táº£i xuá»‘ng, khÃ´ng cÃ³ preview trá»±c tiáº¿p.",
        },
      },
    ],
  },
  {
    id: "stem-grade-1",
    title: "Há»c liá»‡u GiÃ¡o dá»¥c STEM",
    subtitle: "Bá»™ há»c liá»‡u STEM lá»›p 1 - HÃ nh trÃ¬nh sÃ¡ng táº¡o.",
    gradeId: "1",
    subjectId: "giao-duc-stem",
    categoryId: "giao-duc-stem",
    resources: [
      {
        id: "stem-1-teacher-book",
        slug: "stem-1-sach-giao-vien",
        title: "SÃ¡ch giÃ¡o viÃªn",
        subtitle: "GiÃ¡o dá»¥c STEM 1 - HÃ nh trÃ¬nh sÃ¡ng táº¡o",
        gradeId: "1",
        subjectId: "giao-duc-stem",
        categoryId: "giao-duc-stem",
        sectionId: "stem-grade-1",
        resourceType: "teacher_book",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "SÃ¡ch giÃ¡o viÃªn",
        thumbnailTheme: "teal",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 1,
        viewer: {
          title: "SÃ¡ch giÃ¡o viÃªn - STEM 1",
          description: "Reader PDF mÃ´ phá»ng sÃ¡ch giÃ¡o viÃªn STEM.",
          pageCount: 140,
        },
      },
      {
        id: "stem-1-lesson-plan",
        slug: "stem-1-ke-hoach-bai-day",
        title: "Káº¿ hoáº¡ch bÃ i dáº¡y",
        subtitle: "GiÃ¡o dá»¥c STEM 1 - HÃ nh trÃ¬nh sÃ¡ng táº¡o",
        gradeId: "1",
        subjectId: "giao-duc-stem",
        categoryId: "giao-duc-stem",
        sectionId: "stem-grade-1",
        resourceType: "lesson_plan",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "Káº¿ hoáº¡ch bÃ i dáº¡y",
        thumbnailTheme: "teal",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 2,
        viewer: {
          title: "Káº¿ hoáº¡ch bÃ i dáº¡y - STEM 1",
          description: "Danh sÃ¡ch káº¿ hoáº¡ch bÃ i dáº¡y theo chá»§ Ä‘á».",
          pageCount: 40,
        },
      },
      {
        id: "stem-1-slide",
        slug: "stem-1-bai-giang-dien-tu",
        title: "BÃ i giáº£ng Ä‘iá»‡n tá»­",
        subtitle: "GiÃ¡o dá»¥c STEM 1 - HÃ nh trÃ¬nh sÃ¡ng táº¡o",
        gradeId: "1",
        subjectId: "giao-duc-stem",
        categoryId: "giao-duc-stem",
        sectionId: "stem-grade-1",
        resourceType: "slide",
        fileType: "PPTX",
        formatBadge: "PPTX",
        launchMode: "google_slide_embed",
        thumbnailLabel: "BÃ i giáº£ng Ä‘iá»‡n tá»­",
        thumbnailTheme: "teal",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 3,
        viewer: {
          title: "BÃ i giáº£ng Ä‘iá»‡n tá»­ - STEM 1",
          description: "PPTX xem trá»±c tiáº¿p qua Google Slides embed, khÃ´ng lá»™ link gá»‘c.",
          embedUrl: MOCK_SLIDES_EMBED_URL,
          units: [
            { id: "stem-bai-1", title: "BÃ i 1: NgÃ´i nhÃ  mÆ¡ Æ°á»›c" },
            { id: "stem-bai-2", title: "BÃ i 2: Cá»™t Ä‘Ã¨n giao thÃ´ng xoay" },
            { id: "stem-bai-3", title: "BÃ i 3: Dá»¥ng cá»¥ gáº¥p Ã¡o" },
            { id: "stem-bai-4", title: "BÃ i 4: ThÆ°á»›c trÆ°á»£t cá»™ng trá»«" },
          ],
        },
      },
    ],
  },
  {
    id: "ic3-gs6",
    title: "IC3 GS6",
    subtitle: "Digital Literacy theo 3 domain cá»‘t lÃµi.",
    subjectId: "ic3",
    categoryId: "ic3-digital-literacy",
    resources: [
      {
        id: "ic3-gs6-l1-computing",
        slug: "ic3-gs6-level-1-computing-fundamentals",
        title: "IC3 GS6 Level 1 - Computing Fundamentals",
        subtitle: "IC3 Digital Literacy",
        subjectId: "ic3",
        categoryId: "ic3-digital-literacy",
        sectionId: "ic3-gs6",
        resourceType: "pdf",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "IC3 GS6 L1",
        thumbnailTheme: "blue",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 1,
        viewer: {
          title: "IC3 GS6 Level 1 - Computing Fundamentals",
          description: "GiÃ¡o trÃ¬nh ná»n táº£ng mÃ¡y tÃ­nh cho lá»›p IC3.",
          pageCount: 86,
          embedUrl: MOCK_GOOGLE_PDF_EMBED_URL,
        },
      },
      {
        id: "ic3-gs6-key-apps",
        slug: "ic3-gs6-level-1-key-applications",
        title: "IC3 GS6 Level 1 - Key Applications",
        subtitle: "IC3 Digital Literacy",
        subjectId: "ic3",
        categoryId: "ic3-digital-literacy",
        sectionId: "ic3-gs6",
        resourceType: "slide",
        fileType: "PPTX",
        formatBadge: "PPTX",
        launchMode: "google_slide_embed",
        thumbnailLabel: "Key Applications",
        thumbnailTheme: "purple",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 2,
        viewer: {
          title: "IC3 GS6 Level 1 - Key Applications",
          description: "PPTX xem trá»±c tiáº¿p qua Google Slides embed.",
          embedUrl: MOCK_SLIDES_EMBED_URL,
          units: [
            { id: "word", title: "Word processing fundamentals" },
            { id: "spreadsheet", title: "Spreadsheet basics" },
            { id: "presentation", title: "Presentation essentials" },
          ],
        },
      },
      {
        id: "ic3-gs6-living-online",
        slug: "ic3-gs6-living-online",
        title: "IC3 GS6 Level 1 - Living Online",
        subtitle: "IC3 Digital Literacy",
        subjectId: "ic3",
        categoryId: "ic3-digital-literacy",
        sectionId: "ic3-gs6",
        resourceType: "video",
        fileType: "VIDEO",
        formatBadge: "VIDEO",
        launchMode: "video_player",
        thumbnailLabel: "Living Online",
        thumbnailTheme: "green",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 3,
        viewer: {
          title: "IC3 GS6 Level 1 - Living Online",
          description: "Video bÃ i há»c vá» cÃ´ng dÃ¢n sá»‘, tÃ¬m kiáº¿m vÃ  an toÃ n trá»±c tuyáº¿n.",
          duration: "22:10",
        },
      },
      {
        id: "ic3-question-bank",
        slug: "ngan-hang-cau-hoi-ic3-gs6",
        title: "NgÃ¢n hÃ ng cÃ¢u há»i IC3 GS6",
        subtitle: "Mock test vÃ  exit ticket",
        subjectId: "ic3",
        categoryId: "ic3-digital-literacy",
        sectionId: "ic3-gs6",
        resourceType: "quiz",
        fileType: "QUIZ",
        formatBadge: "QUIZ",
        launchMode: "quiz_runtime",
        thumbnailLabel: "Quiz Bank",
        thumbnailTheme: "orange",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 4,
        viewer: {
          title: "NgÃ¢n hÃ ng cÃ¢u há»i IC3 GS6",
          description: "Mock quiz shell Ä‘á»ƒ FE tÃ­ch há»£p quiz runtime sau.",
        },
      },
    ],
  },
  {
    id: "mos-office",
    title: "MOS Word, Excel, PowerPoint",
    subtitle: "TÃ i nguyÃªn luyá»‡n thi Microsoft Office Specialist.",
    subjectId: "mos",
    categoryId: "mos",
    resources: [
      {
        id: "mos-word-book",
        slug: "mos-word-associate-giao-trinh",
        title: "MOS Word Associate - GiÃ¡o trÃ¬nh",
        subtitle: "MOS Word",
        subjectId: "mos",
        categoryId: "mos",
        sectionId: "mos-office",
        resourceType: "pdf",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "MOS Word",
        thumbnailTheme: "blue",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 1,
        viewer: {
          title: "MOS Word Associate - GiÃ¡o trÃ¬nh",
          description: "PDF xem trá»±c tiáº¿p báº±ng Google Drive preview trong modal.",
          pageCount: 112,
          embedUrl: MOCK_GOOGLE_PDF_EMBED_URL,
        },
      },
      {
        id: "mos-excel-slide",
        slug: "mos-excel-associate-bai-giang",
        title: "MOS Excel Associate - BÃ i giáº£ng",
        subtitle: "MOS Excel",
        subjectId: "mos",
        categoryId: "mos",
        sectionId: "mos-office",
        resourceType: "slide",
        fileType: "PPTX",
        formatBadge: "PPTX",
        launchMode: "google_slide_embed",
        thumbnailLabel: "MOS Excel",
        thumbnailTheme: "green",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 2,
        viewer: {
          title: "MOS Excel Associate - BÃ i giáº£ng",
          description: "PPTX xem trá»±c tiáº¿p qua Google Slides embed.",
          embedUrl: MOCK_SLIDES_EMBED_URL,
          units: [
            { id: "formulas", title: "CÃ´ng thá»©c vÃ  hÃ m cÆ¡ báº£n" },
            { id: "tables", title: "Báº£ng dá»¯ liá»‡u vÃ  Ä‘á»‹nh dáº¡ng" },
            { id: "charts", title: "Biá»ƒu Ä‘á»“ vÃ  phÃ¢n tÃ­ch nhanh" },
          ],
        },
      },
      {
        id: "mos-powerpoint-video",
        slug: "mos-powerpoint-video-thao-tac",
        title: "MOS PowerPoint Associate - Video thao tÃ¡c",
        subtitle: "MOS PowerPoint",
        subjectId: "mos",
        categoryId: "mos",
        sectionId: "mos-office",
        resourceType: "video",
        fileType: "VIDEO",
        formatBadge: "VIDEO",
        launchMode: "video_player",
        thumbnailLabel: "PowerPoint",
        thumbnailTheme: "orange",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 3,
        viewer: {
          title: "MOS PowerPoint Associate - Video thao tÃ¡c",
          description: "Video thao tÃ¡c slide master, layout vÃ  animation cÄƒn báº£n.",
          duration: "19:35",
        },
      },
      {
        id: "mos-word-practice-files",
        slug: "file-thuc-hanh-mos-word",
        title: "File thá»±c hÃ nh MOS Word",
        subtitle: "MOS Word",
        subjectId: "mos",
        categoryId: "mos",
        sectionId: "mos-office",
        resourceType: "download_package",
        fileType: "ZIP",
        formatBadge: "ZIP",
        launchMode: "download_only",
        thumbnailLabel: "Practice Files",
        thumbnailTheme: "slate",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 4,
        viewer: {
          title: "File thá»±c hÃ nh MOS Word",
          description: "GÃ³i file luyá»‡n thao tÃ¡c, khÃ´ng preview trá»±c tiáº¿p.",
        },
      },
    ],
  },
  {
    id: "tin-hoc-pho-thong",
    title: "Tin há»c phá»• thÃ´ng",
    subtitle: "Tin há»c, Scratch, Python vÃ  bÃ i táº­p thá»±c hÃ nh.",
    subjectId: "tin-hoc",
    categoryId: "tin-hoc-pho-thong",
    resources: [
      {
        id: "tin-hoc-6-may-tinh-cong-dong",
        slug: "tin-hoc-6-may-tinh-va-cong-dong",
        title: "Tin há»c 6 - Chá»§ Ä‘á» mÃ¡y tÃ­nh vÃ  cá»™ng Ä‘á»“ng",
        subtitle: "Tin há»c THCS",
        gradeId: "6",
        subjectId: "tin-hoc",
        categoryId: "tin-hoc-pho-thong",
        sectionId: "tin-hoc-pho-thong",
        resourceType: "pdf",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "Tin há»c 6",
        thumbnailTheme: "blue",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 1,
        viewer: {
          title: "Tin há»c 6 - MÃ¡y tÃ­nh vÃ  cá»™ng Ä‘á»“ng",
          description: "PDF xem trá»±c tiáº¿p báº±ng Google Drive preview trong modal.",
          pageCount: 42,
          embedUrl: MOCK_GOOGLE_PDF_EMBED_URL,
        },
      },
      {
        id: "scratch-can-ban-slide",
        slug: "scratch-can-ban-bai-giang-dien-tu",
        title: "Scratch cÄƒn báº£n - BÃ i giáº£ng Ä‘iá»‡n tá»­",
        subtitle: "Láº­p trÃ¬nh Scratch",
        subjectId: "tin-hoc",
        categoryId: "scratch-python",
        sectionId: "tin-hoc-pho-thong",
        resourceType: "slide",
        fileType: "PPTX",
        formatBadge: "PPTX",
        launchMode: "google_slide_embed",
        thumbnailLabel: "Scratch",
        thumbnailTheme: "orange",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 2,
        viewer: {
          title: "Scratch cÄƒn báº£n - BÃ i giáº£ng Ä‘iá»‡n tá»­",
          description: "Slide deck xem trá»±c tiáº¿p qua Google Slides embed.",
          embedUrl: MOCK_SLIDES_EMBED_URL,
          units: [
            { id: "sprite", title: "NhÃ¢n váº­t vÃ  sÃ¢n kháº¥u" },
            { id: "motion", title: "Lá»‡nh chuyá»ƒn Ä‘á»™ng" },
            { id: "event", title: "Sá»± kiá»‡n vÃ  tÆ°Æ¡ng tÃ¡c" },
          ],
        },
      },
      {
        id: "python-thieu-nhi-video",
        slug: "python-thieu-nhi-video-bai-hoc",
        title: "Python thiáº¿u nhi - Video bÃ i há»c",
        subtitle: "Python cÄƒn báº£n",
        subjectId: "tin-hoc",
        categoryId: "scratch-python",
        sectionId: "tin-hoc-pho-thong",
        resourceType: "video",
        fileType: "VIDEO",
        formatBadge: "VIDEO",
        launchMode: "video_player",
        thumbnailLabel: "Python",
        thumbnailTheme: "green",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 3,
        viewer: {
          title: "Python thiáº¿u nhi - Video bÃ i há»c",
          description: "Video player cho bÃ i Python nháº­p mÃ´n.",
          duration: "24:08",
        },
      },
      {
        id: "tin-hoc-7-quiz",
        slug: "trac-nghiem-tin-hoc-7",
        title: "Tráº¯c nghiá»‡m Tin há»c 7",
        subtitle: "Tin há»c THCS",
        gradeId: "7",
        subjectId: "tin-hoc",
        categoryId: "tin-hoc-pho-thong",
        sectionId: "tin-hoc-pho-thong",
        resourceType: "quiz",
        fileType: "QUIZ",
        formatBadge: "QUIZ",
        launchMode: "quiz_runtime",
        thumbnailLabel: "Quiz Tin há»c",
        thumbnailTheme: "purple",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 4,
        viewer: {
          title: "Tráº¯c nghiá»‡m Tin há»c 7",
          description: "Quiz runtime placeholder cho bÃ i kiá»ƒm tra Tin há»c.",
        },
      },
    ],
  },
];

export const DEFAULT_HOCLIEU_SELECTION = {
  gradeId: "1",
  subjectId: "tieng-anh",
  categoryId: "sach-mem-2",
};

export function getCategoryChildren(parentId: string) {
  return HOCLIEU_CATEGORIES.filter((category) => category.parentId === parentId);
}

export function getTopLevelCategories() {
  return HOCLIEU_CATEGORIES.filter((category) => !category.parentId);
}

export function getHocLieuResourceById(resourceId: string) {
  return HOCLIEU_LIBRARY_SECTIONS.flatMap((section) => section.resources).find((resource) => resource.id === resourceId);
}
