export type LearningResourceFileType =
  | "PDF"
  | "PPTX"
  | "VIDEO"
  | "AUDIO"
  | "HTML5"
  | "LINK"
  | "QUIZ"
  | "ZIP"
  | "DOCX"
  | "XLSX"
  | "IMAGE";

export type LearningResourceLaunchMode =
  | "pdf_reader"
  | "ebook_reader"
  | "google_slide_embed"
  | "custom_slide_viewer"
  | "slide_image_proxy"
  | "video_player"
  | "audio_player"
  | "html5_embed"
  | "quiz_runtime"
  | "download_only"
  | "external";

export type LearningResourcePriceType = "free" | "paid" | "licensed";
export type LearningResourceAccessState = "open" | "login_required" | "license_required" | "unavailable";

export type LearningResourceGrade = {
  id: string;
  label: string;
};

export type LearningResourceSubject = {
  id: string;
  label: string;
  gradeIds?: string[];
};

export type LearningResourceCategory = {
  id: string;
  label: string;
  parentId?: string;
  icon: "book" | "document" | "stem" | "certificate" | "computer" | "smart";
};

export type LearningResourceResourceSection = {
  id: string;
  title: string;
  subtitle?: string;
  gradeId?: string;
  subjectId: string;
  categoryId: string;
  resources: LearningResourceResource[];
};

export type LearningResourceViewerUnit = {
  id: string;
  title: string;
  children?: Array<{ id: string; title: string; duration?: string }>;
};

export type LearningResourceViewerSlide = {
  id: string;
  index: number;
  title?: string;
  imageUrl: string;
  thumbnailUrl?: string;
};

export type LearningResourceResource = {
  id: string;
  slug: string;
  title: string;
  subtitle?: string;
  gradeId?: string;
  subjectId: string;
  categoryId: string;
  sectionId: string;
  topicId?: string;
  bookSeriesId?: string;
  resourceType:
    | "ebook"
    | "pdf"
    | "audio"
    | "lesson_plan"
    | "slide"
    | "teacher_book"
    | "test_bank"
    | "video"
    | "lecture_bank"
    | "image_bank"
    | "quiz"
    | "download_package"
    | "interactive"
    | "external_link";
  fileType: LearningResourceFileType;
  formatBadge: string;
  launchMode: LearningResourceLaunchMode;
  thumbnailUrl?: string;
  thumbnailLabel: string;
  thumbnailSubLabel?: string;
  thumbnailTheme: "blue" | "green" | "orange" | "purple" | "teal" | "rose" | "yellow" | "slate";
  priceType: LearningResourcePriceType;
  accessState: LearningResourceAccessState;
  isDownloadable: boolean;
  sortOrder: number;
  viewer: {
    assetId?: string;
    resourceId?: string;
    title: string;
    description: string;
    pageCount?: number;
    duration?: string;
    embedUrl?: string;
    secureEmbedUrl?: string;
    launchUrl?: string;
    presentationTitle?: string;
    slides?: LearningResourceViewerSlide[];
    units?: LearningResourceViewerUnit[];
  };
};

export const LEARNING_RESOURCE_GRADES: LearningResourceGrade[] = [
  { id: "mam-non", label: "Mầm non" },
  ...Array.from({ length: 12 }, (_, index) => {
    const value = String(index + 1);
    return { id: value, label: value };
  }),
];

export const LEARNING_RESOURCE_SUBJECTS: LearningResourceSubject[] = [
  { id: "all", label: "Tất cả" },
  { id: "toan", label: "Toán" },
  { id: "tieng-viet", label: "Tiếng Việt" },
  { id: "tu-nhien-xa-hoi", label: "Tự nhiên và Xã hội", gradeIds: ["1", "2", "3"] },
  { id: "ngu-van", label: "Ngữ văn" },
  { id: "tieng-anh", label: "Tiếng Anh" },
  { id: "khoa-hoc-tu-nhien", label: "Khoa học tự nhiên" },
  { id: "lich-su-dia-li", label: "Lịch sử và Địa lí" },
  { id: "giao-duc-stem", label: "Giáo dục STEM" },
  { id: "giao-duc-ki-nang-cong-dan-so", label: "Giáo dục Kĩ năng Công dân số" },
  { id: "tin-hoc", label: "Tin học" },
  { id: "ic3", label: "IC3" },
  { id: "mos", label: "MOS" },
];

export const LEARNING_RESOURCE_CATEGORIES: LearningResourceCategory[] = [
  { id: "nhat-ki-ngay-he-vui", label: "Nhật kí ngày hè vui", icon: "document" },
  { id: "sgk-tieng-anh", label: "Học liệu SGK Tiếng Anh", icon: "book" },
  { id: "sach-mem-2", label: "Sách Mềm 2.0", parentId: "sgk-tieng-anh", icon: "document" },
  { id: "hop-phan-bo-tro", label: "Hợp phần bổ trợ", parentId: "sgk-tieng-anh", icon: "document" },
  { id: "tieng-anh-tang-cuong", label: "Tiếng Anh Tăng Cường", icon: "book" },
  { id: "global-maths", label: "Global Maths", parentId: "tieng-anh-tang-cuong", icon: "document" },
  { id: "global-science", label: "Global Science", parentId: "tieng-anh-tang-cuong", icon: "document" },
  { id: "hoc-lieu-thong-minh", label: "Học liệu Thông minh", icon: "smart" },
  { id: "ket-noi-tri-thuc", label: "Kết nối tri thức với cuộc sống", parentId: "hoc-lieu-thong-minh", icon: "document" },
  { id: "chan-troi-sang-tao", label: "Chân trời sáng tạo", parentId: "hoc-lieu-thong-minh", icon: "document" },
  { id: "cung-hoc-phat-trien", label: "Cùng học để phát triển năng lực", parentId: "hoc-lieu-thong-minh", icon: "document" },
  { id: "theo-sgk-khac", label: "Theo SGK khác", parentId: "hoc-lieu-thong-minh", icon: "document" },
  { id: "hoc-lieu-giao-duc-khac", label: "Học liệu Giáo dục khác", icon: "stem" },
  { id: "giao-duc-stem", label: "Học liệu Giáo dục STEM", parentId: "hoc-lieu-giao-duc-khac", icon: "stem" },
  { id: "hoc-lieu-sach-tham-khao", label: "Học liệu Sách tham khảo", parentId: "hoc-lieu-giao-duc-khac", icon: "document" },
  { id: "hoc-lieu-hanh-trang-cong-dan-so", label: "Học liệu Hành trang công dân số", parentId: "hoc-lieu-giao-duc-khac", icon: "document" },
  { id: "hoc-lieu-tin-hoc", label: "Học liệu Tin học", icon: "computer" },
  { id: "tin-hoc-pho-thong", label: "Tin học phổ thông", parentId: "hoc-lieu-tin-hoc", icon: "computer" },
  { id: "scratch-python", label: "Scratch & Python", parentId: "hoc-lieu-tin-hoc", icon: "computer" },
  { id: "chung-chi-tin-hoc", label: "Chứng chỉ Tin học", icon: "certificate" },
  { id: "ic3-digital-literacy", label: "IC3 Digital Literacy", parentId: "chung-chi-tin-hoc", icon: "certificate" },
  { id: "mos", label: "MOS", parentId: "chung-chi-tin-hoc", icon: "certificate" },
];

const MOCK_GOOGLE_PDF_EMBED_URL = "/mock/hoclieu/global-success-preview.b64";
const MOCK_SLIDES_EMBED_URL = "/mock/hoclieu/slide-preview.html";

const commonLectureUnits: LearningResourceViewerUnit[] = [
  {
    id: "unit-1",
    title: "Unit 1: My new school",
    children: [
      { id: "lesson-1", title: "Unit 1_Lesson 1_Period 1", duration: "35 phút" },
      { id: "lesson-2", title: "Unit 1_Lesson 2_Period 2", duration: "35 phút" },
      { id: "lesson-3", title: "Unit 1_Lesson 3_Period 3", duration: "35 phút" },
    ],
  },
  { id: "unit-2", title: "Unit 2: My house" },
  { id: "unit-3", title: "Unit 3: My friends" },
  { id: "unit-4", title: "Unit 4: My neighbourhood" },
  { id: "unit-5", title: "Unit 5: Natural wonders of Viet Nam" },
  { id: "unit-6", title: "Unit 6: Our Tet holiday" },
  { id: "unit-7", title: "Unit 7: Television" },
  { id: "unit-8", title: "Unit 8: Sports and Games" },
  { id: "unit-9", title: "Unit 9: Cities of the World" },
];

export const LEARNING_RESOURCE_LIBRARY_SECTIONS: LearningResourceResourceSection[] = [
  {
    id: "nhat-ki-ngay-he-vui",
    title: "NHẬT KÍ NGÀY HÈ VUI",
    subtitle: "Học liệu hè cho học sinh lớp 1, mở nhanh từ kho học liệu.",
    gradeId: "1",
    subjectId: "all",
    categoryId: "nhat-ki-ngay-he-vui",
    resources: [
      {
        id: "nhat-ki-ngay-he-vui-lop-1",
        slug: "nhat-ki-ngay-he-vui-lop-1",
        title: "Nhật kí ngày hè vui Lớp 1",
        subtitle: "Bộ học liệu tích hợp Toán, Tiếng Việt, Tiếng Anh",
        gradeId: "1",
        subjectId: "all",
        categoryId: "nhat-ki-ngay-he-vui",
        sectionId: "nhat-ki-ngay-he-vui",
        resourceType: "interactive",
        fileType: "HTML5",
        formatBadge: "HTML5",
        launchMode: "html5_embed",
        thumbnailLabel: "Nhật kí ngày hè vui",
        thumbnailSubLabel: "Lớp 1",
        thumbnailTheme: "blue",
        priceType: "licensed",
        accessState: "license_required",
        isDownloadable: false,
        sortOrder: 1,
        viewer: {
          title: "Nhật kí ngày hè vui Lớp 1",
          description: "Học liệu HTML5 mô phỏng thao tác kích hoạt sử dụng và mở bài học.",
          embedUrl: MOCK_SLIDES_EMBED_URL,
          units: [
            { id: "nk-bai-1", title: "Tuần 1: Khởi động mùa hè" },
            { id: "nk-bai-2", title: "Tuần 2: Ôn tập Toán và Tiếng Việt" },
            { id: "nk-bai-3", title: "Tuần 3: Em kể chuyện ngày hè" },
          ],
        },
      },
    ],
  },
  {
    id: "sach-mem-2-lop-1",
    title: "HỌC LIỆU SGK TIẾNG ANH",
    subtitle: "Sách Mềm 2.0",
    gradeId: "1",
    subjectId: "tieng-anh",
    categoryId: "sach-mem-2",
    resources: [
      {
        id: "global-success-1-student-book",
        slug: "tieng-anh-1-global-success-sach-hoc-sinh",
        title: "Tiếng Anh 1 - Global Success",
        subtitle: "Sách học sinh",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "sach-mem-2",
        sectionId: "sach-mem-2-lop-1",
        resourceType: "ebook",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "ebook_reader",
        thumbnailLabel: "Global Success",
        thumbnailSubLabel: "Phiên bản GV",
        thumbnailTheme: "green",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 1,
        viewer: {
          title: "Tiếng Anh 1 - Global Success",
          description: "PDF xem trực tiếp bằng Google Drive preview trong modal.",
          pageCount: 96,
          embedUrl: MOCK_GOOGLE_PDF_EMBED_URL,
        },
      },
      {
        id: "global-success-1-workbook",
        slug: "tieng-anh-1-global-success-sach-bai-tap",
        title: "Tiếng Anh 1 - Global Success",
        subtitle: "Sách bài tập",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "sach-mem-2",
        sectionId: "sach-mem-2-lop-1",
        resourceType: "pdf",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "Workbook 1",
        thumbnailSubLabel: "Phiên bản GV",
        thumbnailTheme: "yellow",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 2,
        viewer: {
          title: "Tiếng Anh 1 - Global Success - Sách bài tập",
          description: "PDF xem trực tiếp bằng Google Drive preview trong modal.",
          pageCount: 72,
          embedUrl: MOCK_GOOGLE_PDF_EMBED_URL,
        },
      },
    ],
  },
  {
    id: "hop-phan-bo-tro-lop-1",
    title: "Hợp phần bổ trợ",
    gradeId: "1",
    subjectId: "tieng-anh",
    categoryId: "hop-phan-bo-tro",
    resources: [
      {
        id: "global-success-1-audio",
        slug: "global-success-1-audio",
        title: "Audio",
        subtitle: "Tiếng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "audio",
        fileType: "AUDIO",
        formatBadge: "AUDIO",
        launchMode: "audio_player",
        thumbnailLabel: "Audio",
        thumbnailTheme: "teal",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 1,
        viewer: { title: "Audio - Tiếng Anh 1", description: "Danh sách audio theo unit.", duration: "01:12:00" },
      },
      {
        id: "global-success-1-lesson-plan",
        slug: "global-success-1-ke-hoach-day-hoc",
        title: "Kế hoạch dạy học",
        subtitle: "Tiếng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "lesson_plan",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "Kế hoạch dạy học",
        thumbnailTheme: "orange",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 2,
        viewer: { title: "Kế hoạch dạy học - Tiếng Anh 1", description: "PDF kế hoạch dạy học.", pageCount: 32 },
      },
      {
        id: "global-success-1-slide",
        slug: "global-success-1-bai-giang-dien-tu",
        title: "Bài giảng điện tử",
        subtitle: "Tiếng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "slide",
        fileType: "PPTX",
        formatBadge: "PPTX",
        launchMode: "google_slide_embed",
        thumbnailLabel: "Bài giảng điện tử",
        thumbnailTheme: "orange",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 3,
        viewer: { title: "Bài giảng điện tử - Tiếng Anh 1", description: "PPTX xem trực tiếp qua Google Slides embed.", embedUrl: MOCK_SLIDES_EMBED_URL, units: commonLectureUnits },
      },
      {
        id: "global-success-1-demo-lesson",
        slug: "global-success-1-giao-an-minh-hoa",
        title: "Giáo án minh họa",
        subtitle: "Tiếng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "lesson_plan",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "Giáo án minh họa",
        thumbnailTheme: "rose",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 4,
        viewer: { title: "Giáo án minh họa", description: "PDF giáo án minh họa.", pageCount: 18 },
      },
      {
        id: "global-success-1-flashcards",
        slug: "global-success-1-the-tu",
        title: "Thẻ từ",
        subtitle: "Tiếng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "image_bank",
        fileType: "IMAGE",
        formatBadge: "IMAGE",
        launchMode: "external",
        thumbnailLabel: "Thẻ từ",
        thumbnailTheme: "teal",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 5,
        viewer: { title: "Thẻ từ", description: "Bộ thẻ từ dùng trên lớp." },
      },
      {
        id: "global-success-1-situation-cards",
        slug: "global-success-1-tranh-tinh-huong",
        title: "Tranh tình huống",
        subtitle: "Tiếng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "image_bank",
        fileType: "IMAGE",
        formatBadge: "IMAGE",
        launchMode: "external",
        thumbnailLabel: "Tranh tình huống",
        thumbnailTheme: "purple",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 6,
        viewer: { title: "Tranh tình huống", description: "Bộ tranh tình huống theo bài học." },
      },
      {
        id: "global-success-1-puppets",
        slug: "global-success-1-bo-quan-roi",
        title: "Bộ quân rối",
        subtitle: "Tiếng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "image_bank",
        fileType: "IMAGE",
        formatBadge: "IMAGE",
        launchMode: "external",
        thumbnailLabel: "Bộ quân rối",
        thumbnailTheme: "teal",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 7,
        viewer: { title: "Bộ quân rối", description: "Tài nguyên quân rối lớp học." },
      },
      {
        id: "global-success-1-sample-test",
        slug: "global-success-1-de-kiem-tra-minh-hoa",
        title: "Đề kiểm tra minh họa",
        subtitle: "Tiếng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "test_bank",
        fileType: "QUIZ",
        formatBadge: "QUIZ",
        launchMode: "quiz_runtime",
        thumbnailLabel: "Đề kiểm tra minh họa",
        thumbnailTheme: "green",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 8,
        viewer: { title: "Đề kiểm tra minh họa", description: "Bộ đề kiểm tra minh họa." },
      },
      {
        id: "global-success-1-test-bank",
        slug: "global-success-1-ngan-hang-de-kiem-tra",
        title: "Ngân hàng đề kiểm tra",
        subtitle: "Tiếng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "test_bank",
        fileType: "QUIZ",
        formatBadge: "QUIZ",
        launchMode: "quiz_runtime",
        thumbnailLabel: "Ngân hàng đề kiểm tra",
        thumbnailTheme: "green",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 9,
        viewer: { title: "Ngân hàng đề kiểm tra", description: "Ngân hàng câu hỏi kiểm tra." },
      },
      {
        id: "global-success-1-demo-video",
        slug: "global-success-1-video-tiet-day-minh-hoa",
        title: "Video tiết dạy minh họa",
        subtitle: "Tiếng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "video",
        fileType: "VIDEO",
        formatBadge: "VIDEO",
        launchMode: "video_player",
        thumbnailLabel: "Video tiết dạy minh họa",
        thumbnailTheme: "green",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 10,
        viewer: { title: "Video tiết dạy minh họa", description: "Video player tối giản.", duration: "15:28" },
      },
      {
        id: "global-success-1-pronunciation-video",
        slug: "global-success-1-video-huong-dan-phat-am",
        title: "Video hướng dẫn phát âm",
        subtitle: "Tiếng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "video",
        fileType: "VIDEO",
        formatBadge: "VIDEO",
        launchMode: "video_player",
        thumbnailLabel: "Video hướng dẫn phát âm",
        thumbnailTheme: "purple",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 11,
        viewer: { title: "Video hướng dẫn phát âm", description: "Video hướng dẫn phát âm.", duration: "12:02" },
      },
      {
        id: "global-success-1-cartoon",
        slug: "global-success-1-video-hoat-hinh",
        title: "Video hoạt hình",
        subtitle: "Tiếng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "video",
        fileType: "VIDEO",
        formatBadge: "VIDEO",
        launchMode: "video_player",
        thumbnailLabel: "Video hoạt hình",
        thumbnailTheme: "blue",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 12,
        viewer: { title: "Video hoạt hình", description: "Video hoạt hình theo unit.", duration: "10:04" },
      },
      {
        id: "global-success-1-teacher-book",
        slug: "global-success-1-sach-giao-vien",
        title: "Sách giáo viên",
        subtitle: "Tiếng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "teacher_book",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "Sách giáo viên",
        thumbnailTheme: "rose",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 13,
        viewer: { title: "Sách giáo viên - Tiếng Anh 1", description: "PDF sách giáo viên.", pageCount: 156 },
      },
      {
        id: "global-success-1-vocabulary",
        slug: "global-success-1-tong-hop-tu-vung",
        title: "Tổng hợp từ vựng",
        subtitle: "Tiếng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "pdf",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "Tổng hợp từ vựng",
        thumbnailTheme: "yellow",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 14,
        viewer: { title: "Tổng hợp từ vựng", description: "Bảng tổng hợp từ vựng.", pageCount: 24 },
      },
      {
        id: "global-success-1-expanded-pack",
        slug: "global-success-1-tai-nguyen-mo-rong",
        title: "Tài nguyên mở rộng",
        subtitle: "Tiếng Anh 1 - Global Success",
        gradeId: "1",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro-lop-1",
        resourceType: "download_package",
        fileType: "ZIP",
        formatBadge: "ZIP",
        launchMode: "download_only",
        thumbnailLabel: "Tài nguyên mở rộng",
        thumbnailTheme: "rose",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 15,
        viewer: { title: "Tài nguyên mở rộng", description: "Gói tài nguyên mở rộng tải xuống." },
      },
    ],
  },
  {
    id: "sach-mem-2",
    title: "Sách Mềm 2.0",
    subtitle: "Bộ sách học sinh và sách bài tập theo lớp.",
    gradeId: "7",
    subjectId: "tieng-anh",
    categoryId: "sach-mem-2",
    resources: [
      {
        id: "global-success-7-student-book",
        slug: "tieng-anh-7-global-success-sach-hoc-sinh",
        title: "Tiếng Anh 7 - Global Success",
        subtitle: "Sách học sinh",
        gradeId: "7",
        subjectId: "tieng-anh",
        categoryId: "sach-mem-2",
        sectionId: "sach-mem-2",
        resourceType: "ebook",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "ebook_reader",
        thumbnailLabel: "Global Success",
        thumbnailSubLabel: "Phiên bản GV",
        thumbnailTheme: "blue",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 1,
        viewer: {
          title: "Tiếng Anh 7 - Global Success",
          description: "PDF xem trực tiếp bằng Google Drive preview trong modal.",
          pageCount: 128,
          embedUrl: MOCK_GOOGLE_PDF_EMBED_URL,
        },
      },
      {
        id: "global-success-7-workbook",
        slug: "tieng-anh-7-global-success-sach-bai-tap",
        title: "Tiếng Anh 7 - Global Success",
        subtitle: "Sách bài tập",
        gradeId: "7",
        subjectId: "tieng-anh",
        categoryId: "sach-mem-2",
        sectionId: "sach-mem-2",
        resourceType: "pdf",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "Workbook 7",
        thumbnailSubLabel: "Phiên bản GV",
        thumbnailTheme: "yellow",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 2,
        viewer: {
          title: "Tiếng Anh 7 - Global Success - Sách bài tập",
          description: "PDF xem trực tiếp bằng Google Drive preview trong modal.",
          pageCount: 96,
          embedUrl: MOCK_GOOGLE_PDF_EMBED_URL,
        },
      },
    ],
  },
  {
    id: "hop-phan-bo-tro",
    title: "Hợp phần bổ trợ",
    subtitle: "Các tài nguyên đi kèm bài học và bộ sách.",
    gradeId: "7",
    subjectId: "tieng-anh",
    categoryId: "hop-phan-bo-tro",
    resources: [
      {
        id: "global-success-7-audio",
        slug: "global-success-7-audio",
        title: "Audio",
        subtitle: "Tiếng Anh 7 - Global Success",
        gradeId: "7",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro",
        resourceType: "audio",
        fileType: "AUDIO",
        formatBadge: "AUDIO",
        launchMode: "audio_player",
        thumbnailLabel: "Audio",
        thumbnailTheme: "green",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 1,
        viewer: {
          title: "Audio - Tiếng Anh 7",
          description: "Danh sách audio theo unit, dùng player compact.",
          duration: "02:18:00",
        },
      },
      {
        id: "global-success-7-lesson-plan",
        slug: "global-success-7-ke-hoach-day-hoc",
        title: "Kế hoạch dạy học",
        subtitle: "Tiếng Anh 7 - Global Success",
        gradeId: "7",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro",
        resourceType: "lesson_plan",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "Kế hoạch dạy học",
        thumbnailTheme: "blue",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 2,
        viewer: {
          title: "Kế hoạch dạy học",
          description: "PDF xem trực tiếp bằng Google Drive preview trong modal.",
          pageCount: 11,
          embedUrl: MOCK_GOOGLE_PDF_EMBED_URL,
        },
      },
      {
        id: "global-success-7-slide",
        slug: "global-success-7-bai-giang-dien-tu",
        title: "Bài giảng điện tử",
        subtitle: "Tiếng Anh 7 - Global Success",
        gradeId: "7",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro",
        resourceType: "slide",
        fileType: "PPTX",
        formatBadge: "PPTX",
        launchMode: "google_slide_embed",
        thumbnailLabel: "Bài giảng điện tử",
        thumbnailTheme: "orange",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 3,
        viewer: {
          title: "Bài giảng điện tử",
          description: "PPTX xem trực tiếp qua Google Slides embed. UI không hiển thị link gốc.",
          embedUrl: MOCK_SLIDES_EMBED_URL,
          presentationTitle: "Lesson 1 - GETTING STARTED",
          units: commonLectureUnits,
        },
      },
      {
        id: "global-success-7-test-bank",
        slug: "global-success-7-ngan-hang-de-kiem-tra",
        title: "Ngân hàng đề kiểm tra",
        subtitle: "Tiếng Anh 7 - Global Success",
        gradeId: "7",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro",
        resourceType: "test_bank",
        fileType: "QUIZ",
        formatBadge: "QUIZ",
        launchMode: "quiz_runtime",
        thumbnailLabel: "Ngân hàng đề",
        thumbnailTheme: "purple",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 4,
        viewer: {
          title: "Ngân hàng đề kiểm tra",
          description: "Điều hướng sang quiz/runtime khi BE cung cấp package thật.",
        },
      },
      {
        id: "global-success-7-video",
        slug: "global-success-7-video-tiet-day-minh-hoa",
        title: "Video tiết dạy minh họa",
        subtitle: "Tiếng Anh 7 - Global Success",
        gradeId: "7",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro",
        resourceType: "video",
        fileType: "VIDEO",
        formatBadge: "VIDEO",
        launchMode: "video_player",
        thumbnailLabel: "Video tiết dạy",
        thumbnailTheme: "rose",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 5,
        viewer: {
          title: "Video tiết dạy minh họa",
          description: "Video player tối giản, không autoplay.",
          duration: "18:42",
        },
      },
      {
        id: "global-success-7-teacher-pack",
        slug: "global-success-7-file-thuc-hanh",
        title: "File thực hành lớp học",
        subtitle: "Tiếng Anh 7 - Global Success",
        gradeId: "7",
        subjectId: "tieng-anh",
        categoryId: "hop-phan-bo-tro",
        sectionId: "hop-phan-bo-tro",
        resourceType: "download_package",
        fileType: "ZIP",
        formatBadge: "ZIP",
        launchMode: "download_only",
        thumbnailLabel: "Practice Pack",
        thumbnailTheme: "slate",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 6,
        viewer: {
          title: "File thực hành lớp học",
          description: "Gói tải xuống, không có preview trực tiếp.",
        },
      },
    ],
  },
  {
    id: "stem-grade-1",
    title: "Học liệu Giáo dục STEM",
    subtitle: "Bộ học liệu STEM lớp 1 - Hành trình sáng tạo.",
    gradeId: "1",
    subjectId: "giao-duc-stem",
    categoryId: "giao-duc-stem",
    resources: [
      {
        id: "stem-1-teacher-book",
        slug: "stem-1-sach-giao-vien",
        title: "Sách giáo viên",
        subtitle: "Giáo dục STEM 1 - Hành trình sáng tạo",
        gradeId: "1",
        subjectId: "giao-duc-stem",
        categoryId: "giao-duc-stem",
        sectionId: "stem-grade-1",
        resourceType: "teacher_book",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "Sách giáo viên",
        thumbnailTheme: "teal",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 1,
        viewer: {
          title: "Sách giáo viên - STEM 1",
          description: "Reader PDF mô phỏng sách giáo viên STEM.",
          pageCount: 140,
        },
      },
      {
        id: "stem-1-lesson-plan",
        slug: "stem-1-ke-hoach-bai-day",
        title: "Kế hoạch bài dạy",
        subtitle: "Giáo dục STEM 1 - Hành trình sáng tạo",
        gradeId: "1",
        subjectId: "giao-duc-stem",
        categoryId: "giao-duc-stem",
        sectionId: "stem-grade-1",
        resourceType: "lesson_plan",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "Kế hoạch bài dạy",
        thumbnailTheme: "teal",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 2,
        viewer: {
          title: "Kế hoạch bài dạy - STEM 1",
          description: "Danh sách kế hoạch bài dạy theo chủ đề.",
          pageCount: 40,
        },
      },
      {
        id: "stem-1-slide",
        slug: "stem-1-bai-giang-dien-tu",
        title: "Bài giảng điện tử",
        subtitle: "Giáo dục STEM 1 - Hành trình sáng tạo",
        gradeId: "1",
        subjectId: "giao-duc-stem",
        categoryId: "giao-duc-stem",
        sectionId: "stem-grade-1",
        resourceType: "slide",
        fileType: "PPTX",
        formatBadge: "PPTX",
        launchMode: "google_slide_embed",
        thumbnailLabel: "Bài giảng điện tử",
        thumbnailTheme: "teal",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 3,
        viewer: {
          title: "Bài giảng điện tử - STEM 1",
          description: "PPTX xem trực tiếp qua Google Slides embed, không lộ link gốc.",
          embedUrl: MOCK_SLIDES_EMBED_URL,
          units: [
            { id: "stem-bai-1", title: "Bài 1: Ngôi nhà mơ ước" },
            { id: "stem-bai-2", title: "Bài 2: Cột đèn giao thông xoay" },
            { id: "stem-bai-3", title: "Bài 3: Dụng cụ gấp áo" },
            { id: "stem-bai-4", title: "Bài 4: Thước trượt cộng trừ" },
          ],
        },
      },
    ],
  },
  {
    id: "ic3-gs6",
    title: "IC3 GS6",
    subtitle: "Digital Literacy theo 3 domain cốt lõi.",
    subjectId: "ic3",
    categoryId: "ic3-digital-literacy",
    resources: [
      {
        id: "ic3-gs6-l1-computing",
        slug: "ic3-gs6-level-1-computing-fundamentals",
        title: "IC3 GS6 Level 1 - Computing Fundamentals",
        subtitle: "IC3 Digital Literacy",
        subjectId: "ic3",
        categoryId: "ic3-digital-literacy",
        sectionId: "ic3-gs6",
        resourceType: "pdf",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "IC3 GS6 L1",
        thumbnailTheme: "blue",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 1,
        viewer: {
          title: "IC3 GS6 Level 1 - Computing Fundamentals",
          description: "Giáo trình nền tảng máy tính cho lớp IC3.",
          pageCount: 86,
          embedUrl: MOCK_GOOGLE_PDF_EMBED_URL,
        },
      },
      {
        id: "ic3-gs6-key-apps",
        slug: "ic3-gs6-level-1-key-applications",
        title: "IC3 GS6 Level 1 - Key Applications",
        subtitle: "IC3 Digital Literacy",
        subjectId: "ic3",
        categoryId: "ic3-digital-literacy",
        sectionId: "ic3-gs6",
        resourceType: "slide",
        fileType: "PPTX",
        formatBadge: "PPTX",
        launchMode: "google_slide_embed",
        thumbnailLabel: "Key Applications",
        thumbnailTheme: "purple",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 2,
        viewer: {
          title: "IC3 GS6 Level 1 - Key Applications",
          description: "PPTX xem trực tiếp qua Google Slides embed.",
          embedUrl: MOCK_SLIDES_EMBED_URL,
          units: [
            { id: "word", title: "Word processing fundamentals" },
            { id: "spreadsheet", title: "Spreadsheet basics" },
            { id: "presentation", title: "Presentation essentials" },
          ],
        },
      },
      {
        id: "ic3-gs6-living-online",
        slug: "ic3-gs6-living-online",
        title: "IC3 GS6 Level 1 - Living Online",
        subtitle: "IC3 Digital Literacy",
        subjectId: "ic3",
        categoryId: "ic3-digital-literacy",
        sectionId: "ic3-gs6",
        resourceType: "video",
        fileType: "VIDEO",
        formatBadge: "VIDEO",
        launchMode: "video_player",
        thumbnailLabel: "Living Online",
        thumbnailTheme: "green",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 3,
        viewer: {
          title: "IC3 GS6 Level 1 - Living Online",
          description: "Video bài học về công dân số, tìm kiếm và an toàn trực tuyến.",
          duration: "22:10",
        },
      },
      {
        id: "ic3-question-bank",
        slug: "ngan-hang-cau-hoi-ic3-gs6",
        title: "Ngân hàng câu hỏi IC3 GS6",
        subtitle: "Mock test và exit ticket",
        subjectId: "ic3",
        categoryId: "ic3-digital-literacy",
        sectionId: "ic3-gs6",
        resourceType: "quiz",
        fileType: "QUIZ",
        formatBadge: "QUIZ",
        launchMode: "quiz_runtime",
        thumbnailLabel: "Quiz Bank",
        thumbnailTheme: "orange",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 4,
        viewer: {
          title: "Ngân hàng câu hỏi IC3 GS6",
          description: "Mock quiz shell để FE tích hợp quiz runtime sau.",
        },
      },
    ],
  },
  {
    id: "mos-office",
    title: "MOS Word, Excel, PowerPoint",
    subtitle: "Tài nguyên luyện thi Microsoft Office Specialist.",
    subjectId: "mos",
    categoryId: "mos",
    resources: [
      {
        id: "mos-word-book",
        slug: "mos-word-associate-giao-trinh",
        title: "MOS Word Associate - Giáo trình",
        subtitle: "MOS Word",
        subjectId: "mos",
        categoryId: "mos",
        sectionId: "mos-office",
        resourceType: "pdf",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "MOS Word",
        thumbnailTheme: "blue",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 1,
        viewer: {
          title: "MOS Word Associate - Giáo trình",
          description: "PDF xem trực tiếp bằng Google Drive preview trong modal.",
          pageCount: 112,
          embedUrl: MOCK_GOOGLE_PDF_EMBED_URL,
        },
      },
      {
        id: "mos-excel-slide",
        slug: "mos-excel-associate-bai-giang",
        title: "MOS Excel Associate - Bài giảng",
        subtitle: "MOS Excel",
        subjectId: "mos",
        categoryId: "mos",
        sectionId: "mos-office",
        resourceType: "slide",
        fileType: "PPTX",
        formatBadge: "PPTX",
        launchMode: "google_slide_embed",
        thumbnailLabel: "MOS Excel",
        thumbnailTheme: "green",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 2,
        viewer: {
          title: "MOS Excel Associate - Bài giảng",
          description: "PPTX xem trực tiếp qua Google Slides embed.",
          embedUrl: MOCK_SLIDES_EMBED_URL,
          units: [
            { id: "formulas", title: "Công thức và hàm cơ bản" },
            { id: "tables", title: "Bảng dữ liệu và định dạng" },
            { id: "charts", title: "Biểu đồ và phân tích nhanh" },
          ],
        },
      },
      {
        id: "mos-powerpoint-video",
        slug: "mos-powerpoint-video-thao-tac",
        title: "MOS PowerPoint Associate - Video thao tác",
        subtitle: "MOS PowerPoint",
        subjectId: "mos",
        categoryId: "mos",
        sectionId: "mos-office",
        resourceType: "video",
        fileType: "VIDEO",
        formatBadge: "VIDEO",
        launchMode: "video_player",
        thumbnailLabel: "PowerPoint",
        thumbnailTheme: "orange",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 3,
        viewer: {
          title: "MOS PowerPoint Associate - Video thao tác",
          description: "Video thao tác slide master, layout và animation căn bản.",
          duration: "19:35",
        },
      },
      {
        id: "mos-word-practice-files",
        slug: "file-thuc-hanh-mos-word",
        title: "File thực hành MOS Word",
        subtitle: "MOS Word",
        subjectId: "mos",
        categoryId: "mos",
        sectionId: "mos-office",
        resourceType: "download_package",
        fileType: "ZIP",
        formatBadge: "ZIP",
        launchMode: "download_only",
        thumbnailLabel: "Practice Files",
        thumbnailTheme: "slate",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 4,
        viewer: {
          title: "File thực hành MOS Word",
          description: "Gói file luyện thao tác, không preview trực tiếp.",
        },
      },
    ],
  },
  {
    id: "tin-hoc-pho-thong",
    title: "Tin học phổ thông",
    subtitle: "Tin học, Scratch, Python và bài tập thực hành.",
    subjectId: "tin-hoc",
    categoryId: "tin-hoc-pho-thong",
    resources: [
      {
        id: "tin-hoc-6-may-tinh-cong-dong",
        slug: "tin-hoc-6-may-tinh-va-cong-dong",
        title: "Tin học 6 - Chủ đề máy tính và cộng đồng",
        subtitle: "Tin học THCS",
        gradeId: "6",
        subjectId: "tin-hoc",
        categoryId: "tin-hoc-pho-thong",
        sectionId: "tin-hoc-pho-thong",
        resourceType: "pdf",
        fileType: "PDF",
        formatBadge: "PDF",
        launchMode: "pdf_reader",
        thumbnailLabel: "Tin học 6",
        thumbnailTheme: "blue",
        priceType: "free",
        accessState: "open",
        isDownloadable: true,
        sortOrder: 1,
        viewer: {
          title: "Tin học 6 - Máy tính và cộng đồng",
          description: "PDF xem trực tiếp bằng Google Drive preview trong modal.",
          pageCount: 42,
          embedUrl: MOCK_GOOGLE_PDF_EMBED_URL,
        },
      },
      {
        id: "scratch-can-ban-slide",
        slug: "scratch-can-ban-bai-giang-dien-tu",
        title: "Scratch căn bản - Bài giảng điện tử",
        subtitle: "Lập trình Scratch",
        subjectId: "tin-hoc",
        categoryId: "scratch-python",
        sectionId: "tin-hoc-pho-thong",
        resourceType: "slide",
        fileType: "PPTX",
        formatBadge: "PPTX",
        launchMode: "google_slide_embed",
        thumbnailLabel: "Scratch",
        thumbnailTheme: "orange",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 2,
        viewer: {
          title: "Scratch căn bản - Bài giảng điện tử",
          description: "Slide deck xem trực tiếp qua Google Slides embed.",
          embedUrl: MOCK_SLIDES_EMBED_URL,
          units: [
            { id: "sprite", title: "Nhân vật và sân khấu" },
            { id: "motion", title: "Lệnh chuyển động" },
            { id: "event", title: "Sự kiện và tương tác" },
          ],
        },
      },
      {
        id: "python-thieu-nhi-video",
        slug: "python-thieu-nhi-video-bai-hoc",
        title: "Python thiếu nhi - Video bài học",
        subtitle: "Python căn bản",
        subjectId: "tin-hoc",
        categoryId: "scratch-python",
        sectionId: "tin-hoc-pho-thong",
        resourceType: "video",
        fileType: "VIDEO",
        formatBadge: "VIDEO",
        launchMode: "video_player",
        thumbnailLabel: "Python",
        thumbnailTheme: "green",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 3,
        viewer: {
          title: "Python thiếu nhi - Video bài học",
          description: "Video player cho bài Python nhập môn.",
          duration: "24:08",
        },
      },
      {
        id: "tin-hoc-7-quiz",
        slug: "trac-nghiem-tin-hoc-7",
        title: "Trắc nghiệm Tin học 7",
        subtitle: "Tin học THCS",
        gradeId: "7",
        subjectId: "tin-hoc",
        categoryId: "tin-hoc-pho-thong",
        sectionId: "tin-hoc-pho-thong",
        resourceType: "quiz",
        fileType: "QUIZ",
        formatBadge: "QUIZ",
        launchMode: "quiz_runtime",
        thumbnailLabel: "Quiz Tin học",
        thumbnailTheme: "purple",
        priceType: "free",
        accessState: "open",
        isDownloadable: false,
        sortOrder: 4,
        viewer: {
          title: "Trắc nghiệm Tin học 7",
          description: "Quiz runtime placeholder cho bài kiểm tra Tin học.",
        },
      },
    ],
  },
];

export const DEFAULT_LEARNING_RESOURCE_SELECTION = {
  gradeId: "1",
  subjectId: "tieng-anh",
  categoryId: "sach-mem-2",
};

export function getCategoryChildren(parentId: string) {
  return LEARNING_RESOURCE_CATEGORIES.filter((category) => category.parentId === parentId);
}

export function getTopLevelCategories() {
  return LEARNING_RESOURCE_CATEGORIES.filter((category) => !category.parentId);
}

export function getLearningResourceResourceById(resourceId: string) {
  return LEARNING_RESOURCE_LIBRARY_SECTIONS.flatMap((section) => section.resources).find((resource) => resource.id === resourceId);
}
