export const EXPANDED_SIDEBAR_WIDTH = 236;
export const COLLAPSED_SIDEBAR_WIDTH = 72;
export const PORTAL_SIDEBAR_MOTION_MS = 280;
export const PORTAL_SIDEBAR_MOTION_EASING =
  "cubic-bezier(0.2, 0, 0, 1)";
export const PORTAL_SIDEBAR_TRANSITION =
  `${PORTAL_SIDEBAR_MOTION_MS}ms ${PORTAL_SIDEBAR_MOTION_EASING}`;
