import type { CSSProperties } from "react";

import type { Theme } from "@/lib/types";

export type QuizThemePreset = {
  id: string;
  name: string;
  description: string;
  collection: string;
  theme: Theme;
};

export const QUIZ_THEME_STRIP_VISIBLE_COUNT = 6;

export const quizThemePresets: QuizThemePreset[] = [
  {
    id: "erg-classic",
    name: "ERG Classic",
    description: "Navy and red learning theme inspired by the ERG teacher workspace.",
    collection: "This Quiz",
    theme: {
      pageBackground: "#f8fafc",
      playerBackground: "#ffffff",
      canvasBorder: "#dbe5f1",
      headerBackground: "linear-gradient(135deg, #00008b 0%, #1d4ed8 100%)",
      headerText: "#ffffff",
      accentStart: "#00008b",
      accentEnd: "#cc0022",
      optionText: "#214f88",
      optionSelectedBackground: "#eaf1ff",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "linear-gradient(135deg, #00008b 0%, #1d4ed8 100%)",
      sidebarActiveText: "#ffffff",
    },
  },
  {
    id: "harmony-mint",
    name: "Harmony Mint",
    description: "Fresh green gradients with a calm academic mood for daily practice quizzes.",
    collection: "Harmony",
    theme: {
      pageBackground: "#f4fbf5",
      playerBackground: "#fffef8",
      canvasBorder: "#c9dfc9",
      headerBackground: "linear-gradient(135deg, #a7d29b 0%, #d8ead2 100%)",
      headerText: "#2f4f33",
      accentStart: "#7db587",
      accentEnd: "#c5d99a",
      optionText: "#45624b",
      optionSelectedBackground: "#edf6e8",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "linear-gradient(135deg, #8bc69a 0%, #bfd998 100%)",
      sidebarActiveText: "#294530",
    },
  },
  {
    id: "harmony-olive",
    name: "Harmony Olive",
    description: "Soft olive tones and warm paper surfaces for guided lesson content.",
    collection: "Harmony",
    theme: {
      pageBackground: "#fbfbef",
      playerBackground: "#fffef9",
      canvasBorder: "#dcd8ba",
      headerBackground: "linear-gradient(135deg, #dfe6bf 0%, #f4f2d5 100%)",
      headerText: "#4d5533",
      accentStart: "#b8c484",
      accentEnd: "#e6d9b2",
      optionText: "#4f5538",
      optionSelectedBackground: "#f7f5de",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "linear-gradient(135deg, #d4ddb0 0%, #ece3bc 100%)",
      sidebarActiveText: "#4b5232",
    },
  },
  {
    id: "harmony-sky",
    name: "Harmony Sky",
    description: "Airy blue layers that keep the slide canvas bright and easy to scan.",
    collection: "Harmony",
    theme: {
      pageBackground: "#eff6ff",
      playerBackground: "#ffffff",
      canvasBorder: "#c7d8ea",
      headerBackground: "linear-gradient(135deg, #c7d9f7 0%, #e6eefc 100%)",
      headerText: "#35537e",
      accentStart: "#8ab0eb",
      accentEnd: "#cfdcf8",
      optionText: "#3a567e",
      optionSelectedBackground: "#e7eefc",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "linear-gradient(135deg, #b8cdf4 0%, #e4ecfb 100%)",
      sidebarActiveText: "#37537a",
    },
  },
  {
    id: "harmony-cloud",
    name: "Harmony Cloud",
    description: "A slightly cooler blue preset for structured tests and review sessions.",
    collection: "Harmony",
    theme: {
      pageBackground: "#f5f8ff",
      playerBackground: "#ffffff",
      canvasBorder: "#d2dcf2",
      headerBackground: "linear-gradient(135deg, #d8e4fb 0%, #eff4ff 100%)",
      headerText: "#42547a",
      accentStart: "#9ab8ef",
      accentEnd: "#dce6fa",
      optionText: "#44557b",
      optionSelectedBackground: "#edf3ff",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "linear-gradient(135deg, #c7d8f7 0%, #eff4fe 100%)",
      sidebarActiveText: "#425279",
    },
  },
  {
    id: "harmony-coral",
    name: "Harmony Coral",
    description: "Warm coral highlights that feel energetic without overwhelming the slide.",
    collection: "Harmony",
    theme: {
      pageBackground: "#fff8f3",
      playerBackground: "#ffffff",
      canvasBorder: "#f3d3c4",
      headerBackground: "linear-gradient(135deg, #ffd0b4 0%, #ffe9dc 100%)",
      headerText: "#8a4f2d",
      accentStart: "#f6a77b",
      accentEnd: "#ffd2b7",
      optionText: "#8f5837",
      optionSelectedBackground: "#fff0e5",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "linear-gradient(135deg, #ffc3a3 0%, #ffe2d2 100%)",
      sidebarActiveText: "#8a4f2d",
    },
  },
  {
    id: "office-silver",
    name: "Office Silver",
    description: "Neutral metallic surfaces for internal training or process documentation.",
    collection: "Office",
    theme: {
      pageBackground: "#f7f8fa",
      playerBackground: "#ffffff",
      canvasBorder: "#d6dbe4",
      headerBackground: "linear-gradient(135deg, #eef2f7 0%, #dce3ee 100%)",
      headerText: "#4c5563",
      accentStart: "#bac4d3",
      accentEnd: "#eceff5",
      optionText: "#505967",
      optionSelectedBackground: "#edf2f7",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "linear-gradient(135deg, #dfe6ee 0%, #f4f6f9 100%)",
      sidebarActiveText: "#4a5563",
    },
  },
  {
    id: "office-midnight",
    name: "Office Midnight",
    description: "Deep navy surfaces with clear white contrast for executive-style content.",
    collection: "Office",
    theme: {
      pageBackground: "#eef2f7",
      playerBackground: "#ffffff",
      canvasBorder: "#cbd5e1",
      headerBackground: "linear-gradient(135deg, #1f2937 0%, #111827 100%)",
      headerText: "#f8fafc",
      accentStart: "#0f172a",
      accentEnd: "#334155",
      optionText: "#1e293b",
      optionSelectedBackground: "#e2e8f0",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "linear-gradient(135deg, #0f172a 0%, #334155 100%)",
      sidebarActiveText: "#f8fafc",
    },
  },
  {
    id: "office-frost",
    name: "Office Frost",
    description: "Soft ice blue panels and pale neutrals for modern classroom dashboards.",
    collection: "Office",
    theme: {
      pageBackground: "#f1f7f9",
      playerBackground: "#ffffff",
      canvasBorder: "#c9d9dd",
      headerBackground: "linear-gradient(135deg, #bdd2d7 0%, #eef5f7 100%)",
      headerText: "#37505b",
      accentStart: "#9bbbc2",
      accentEnd: "#dae9ec",
      optionText: "#425b66",
      optionSelectedBackground: "#e9f1f3",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "linear-gradient(135deg, #b3ccd2 0%, #eef5f7 100%)",
      sidebarActiveText: "#36505a",
    },
  },
  {
    id: "office-paper",
    name: "Office Paper",
    description: "Cream paper tones with understated accents for policy and reading slides.",
    collection: "Office",
    theme: {
      pageBackground: "#fcf7f0",
      playerBackground: "#fffdfa",
      canvasBorder: "#e8dccd",
      headerBackground: "linear-gradient(135deg, #efe4d6 0%, #f9f4ec 100%)",
      headerText: "#6c5441",
      accentStart: "#d8c1a8",
      accentEnd: "#efe3d2",
      optionText: "#6e5643",
      optionSelectedBackground: "#f8efe3",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "linear-gradient(135deg, #e9d9c6 0%, #f8efe5 100%)",
      sidebarActiveText: "#6a513e",
    },
  },
  {
    id: "kaleidoscope-confetti",
    name: "Kaleidoscope Confetti",
    description: "Playful peach and blue accents for younger learners or celebratory screens.",
    collection: "Kaleidoscope",
    theme: {
      pageBackground: "#fffaf0",
      playerBackground: "#ffffff",
      canvasBorder: "#f0dec4",
      headerBackground: "linear-gradient(135deg, #ffe4b4 0%, #ffd29a 48%, #f7f1d0 100%)",
      headerText: "#795433",
      accentStart: "#f4b35c",
      accentEnd: "#7ca8ff",
      optionText: "#6c553d",
      optionSelectedBackground: "#fff1d5",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "linear-gradient(135deg, #ffd9a4 0%, #ffeecf 100%)",
      sidebarActiveText: "#76502f",
    },
  },
  {
    id: "kaleidoscope-prism",
    name: "Kaleidoscope Prism",
    description: "A brighter preset with balanced blues and apricot highlights for mixed media.",
    collection: "Kaleidoscope",
    theme: {
      pageBackground: "#fffdf7",
      playerBackground: "#ffffff",
      canvasBorder: "#d8dff5",
      headerBackground: "linear-gradient(135deg, #f7d8b0 0%, #e2ecff 58%, #fef6d0 100%)",
      headerText: "#50506b",
      accentStart: "#87aefb",
      accentEnd: "#f6b474",
      optionText: "#52526d",
      optionSelectedBackground: "#eef4ff",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "linear-gradient(135deg, #dfe8ff 0%, #fff1d5 100%)",
      sidebarActiveText: "#52536d",
    },
  },
  {
    id: "flow-mint",
    name: "Flow Mint",
    description: "Light mint ribbons with a gentle gradient for friendly lesson intros.",
    collection: "Flowing Lines",
    theme: {
      pageBackground: "#edfff4",
      playerBackground: "#ffffff",
      canvasBorder: "#bfe3cc",
      headerBackground: "linear-gradient(135deg, #8fe1b4 0%, #d7f4e2 100%)",
      headerText: "#2d5a43",
      accentStart: "#6ed099",
      accentEnd: "#b2ebcf",
      optionText: "#35614a",
      optionSelectedBackground: "#def9ea",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "linear-gradient(135deg, #8ee0b0 0%, #d6f5e4 100%)",
      sidebarActiveText: "#2d5a43",
    },
  },
  {
    id: "flow-ocean",
    name: "Flow Ocean",
    description: "Blue motion-inspired preset that keeps analytical quizzes feeling light.",
    collection: "Flowing Lines",
    theme: {
      pageBackground: "#eff7ff",
      playerBackground: "#ffffff",
      canvasBorder: "#bcd6f2",
      headerBackground: "linear-gradient(135deg, #88b9ff 0%, #dbe9ff 100%)",
      headerText: "#2e4e76",
      accentStart: "#6da4f2",
      accentEnd: "#bfd7ff",
      optionText: "#35547c",
      optionSelectedBackground: "#e6f0ff",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "linear-gradient(135deg, #8eb8ff 0%, #dfeafd 100%)",
      sidebarActiveText: "#2d4d76",
    },
  },
  {
    id: "flow-violet",
    name: "Flow Violet",
    description: "Lavender movement and softer contrast for reflective learning content.",
    collection: "Flowing Lines",
    theme: {
      pageBackground: "#f6f0ff",
      playerBackground: "#ffffff",
      canvasBorder: "#d2c2ec",
      headerBackground: "linear-gradient(135deg, #b295e5 0%, #dccbf8 100%)",
      headerText: "#4e4068",
      accentStart: "#9f7de0",
      accentEnd: "#ceb8f2",
      optionText: "#54466d",
      optionSelectedBackground: "#efe6ff",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "linear-gradient(135deg, #ae90e0 0%, #dccdf6 100%)",
      sidebarActiveText: "#4e3f68",
    },
  },
  {
    id: "flow-rose",
    name: "Flow Rose",
    description: "Rose and blush gradients for softer storytelling or onboarding sequences.",
    collection: "Flowing Lines",
    theme: {
      pageBackground: "#fff2f6",
      playerBackground: "#ffffff",
      canvasBorder: "#edc3d0",
      headerBackground: "linear-gradient(135deg, #e9a8be 0%, #f5d2dc 100%)",
      headerText: "#6d4050",
      accentStart: "#d98aa5",
      accentEnd: "#efbfd0",
      optionText: "#714658",
      optionSelectedBackground: "#fde6ee",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "linear-gradient(135deg, #e5a1b7 0%, #f6d5de 100%)",
      sidebarActiveText: "#6b4150",
    },
  },
  {
    id: "geometric-indigo",
    name: "Geometric Indigo",
    description: "Stronger dark indigo contrast for dramatic section breaks or scoring slides.",
    collection: "Geometric",
    theme: {
      pageBackground: "#eef3ff",
      playerBackground: "#ffffff",
      canvasBorder: "#b8c4ee",
      headerBackground: "linear-gradient(135deg, #233a78 0%, #3756a8 100%)",
      headerText: "#f8fbff",
      accentStart: "#274690",
      accentEnd: "#6da0ff",
      optionText: "#20345f",
      optionSelectedBackground: "#dde8ff",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "linear-gradient(135deg, #233a78 0%, #4264bc 100%)",
      sidebarActiveText: "#f8fbff",
    },
  },
  {
    id: "geometric-plum",
    name: "Geometric Plum",
    description: "Dark plum cards with richer accent pops for formal assessment recaps.",
    collection: "Geometric",
    theme: {
      pageBackground: "#f3eef9",
      playerBackground: "#ffffff",
      canvasBorder: "#c8bddb",
      headerBackground: "linear-gradient(135deg, #4c2c6f 0%, #6f4697 100%)",
      headerText: "#fbf8ff",
      accentStart: "#5d347f",
      accentEnd: "#a574d3",
      optionText: "#43295d",
      optionSelectedBackground: "#e8dcf6",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "linear-gradient(135deg, #4d2d70 0%, #784aa7 100%)",
      sidebarActiveText: "#fbf8ff",
    },
  },
  {
    id: "geometric-ruby",
    name: "Geometric Ruby",
    description: "A deeper red preset for checkpoints, outcomes, and decisive callouts.",
    collection: "Geometric",
    theme: {
      pageBackground: "#fdf1f3",
      playerBackground: "#ffffff",
      canvasBorder: "#e2bcc4",
      headerBackground: "linear-gradient(135deg, #7d1732 0%, #a11f45 100%)",
      headerText: "#fff7f9",
      accentStart: "#8f1d3c",
      accentEnd: "#d96889",
      optionText: "#6b1a30",
      optionSelectedBackground: "#fde3ea",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "linear-gradient(135deg, #7e1833 0%, #ae2d53 100%)",
      sidebarActiveText: "#fff7f9",
    },
  },
  {
    id: "geometric-forest",
    name: "Geometric Forest",
    description: "Dark green blocks with bright accents for focused knowledge checks.",
    collection: "Geometric",
    theme: {
      pageBackground: "#eef8f1",
      playerBackground: "#ffffff",
      canvasBorder: "#bdd8c3",
      headerBackground: "linear-gradient(135deg, #1d5b2a 0%, #2d7a3a 100%)",
      headerText: "#f3fdf5",
      accentStart: "#247238",
      accentEnd: "#56b560",
      optionText: "#214d2c",
      optionSelectedBackground: "#dcf3df",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "linear-gradient(135deg, #205f2d 0%, #338544 100%)",
      sidebarActiveText: "#f3fdf5",
    },
  },
];

export const defaultQuizTheme = quizThemePresets[0];

export const groupedQuizThemePresets = quizThemePresets.reduce<Record<string, QuizThemePreset[]>>((groups, preset) => {
  if (!groups[preset.collection]) {
    groups[preset.collection] = [];
  }

  groups[preset.collection].push(preset);
  return groups;
}, {});

export function getQuizThemePreset(themeId?: string) {
  return quizThemePresets.find((preset) => preset.id === themeId) ?? defaultQuizTheme;
}

export function resolveQuizTheme(themeId?: string, themeOverride?: Partial<Theme> | null): Theme {
  return {
    ...getQuizThemePreset(themeId).theme,
    ...(themeOverride ?? {}),
  };
}

export function getQuizThemeStyle(theme: Theme): CSSProperties {
  return {
    ["--quiz-page-bg" as string]: theme.pageBackground,
    ["--quiz-player-bg" as string]: theme.playerBackground,
    ["--quiz-canvas-border" as string]: theme.canvasBorder,
    ["--quiz-header-bg" as string]: theme.headerBackground,
    ["--quiz-header-text" as string]: theme.headerText,
    ["--quiz-accent-start" as string]: theme.accentStart,
    ["--quiz-accent-end" as string]: theme.accentEnd,
    ["--quiz-option-text" as string]: theme.optionText,
    ["--quiz-option-selected-bg" as string]: theme.optionSelectedBackground,
    ["--quiz-input-bg" as string]: theme.inputBackground,
    ["--quiz-sidebar-active-bg" as string]: theme.sidebarActiveBackground,
    ["--quiz-sidebar-active-text" as string]: theme.sidebarActiveText,
  } as CSSProperties;
}

export function getQuizThemeSwatchStyle(theme: Theme): CSSProperties {
  return {
    background: [
      "radial-gradient(circle at 24% 22%, rgba(255,255,255,0.98) 0, rgba(255,255,255,0.52) 25%, transparent 26%)",
      `radial-gradient(circle at 82% 10%, ${theme.optionSelectedBackground} 0, ${theme.optionSelectedBackground} 22%, transparent 23%)`,
      `linear-gradient(135deg, ${theme.playerBackground} 0%, ${theme.pageBackground} 68%, ${theme.optionSelectedBackground} 100%)`,
    ].join(", "),
  };
}

export function getQuizThemeDeckStyle(themeId?: string): CSSProperties {
  const theme = getQuizThemePreset(themeId).theme;

  return {
    ["--classic-slide-bg" as string]: `linear-gradient(135deg, ${theme.playerBackground} 0%, ${theme.pageBackground} 100%)`,
    ["--classic-slide-border" as string]: theme.canvasBorder,
    ["--classic-slide-text" as string]: theme.optionText,
    ["--classic-slide-choice-bg" as string]: theme.optionSelectedBackground,
    ["--classic-slide-choice-border" as string]: theme.canvasBorder,
    ["--classic-slide-card-bg" as string]: theme.playerBackground,
    ["--classic-slide-card-text" as string]: theme.optionText,
    ["--classic-slide-accent-gradient" as string]: theme.headerBackground,
    ["--classic-slide-accent-soft" as string]: theme.accentStart,
    ["--classic-slide-accent-strong" as string]: theme.accentEnd,
    ["--classic-slide-result-pass-bg" as string]: theme.accentStart,
    ["--classic-slide-result-fail-bg" as string]: theme.accentEnd,
    ["--classic-slide-result-copy" as string]: theme.optionText,
    ["--classic-slide-result-target-correct" as string]: theme.accentStart,
    ["--classic-slide-result-target-wrong" as string]: theme.accentEnd,
  } as CSSProperties;
}
