import type { CSSProperties } from "react";

import type { Theme } from "@/lib/types";

export type QuizThemePreset = {
  id: string;
  name: string;
  description: string;
  collection: string;
  theme: Theme;
};

export const QUIZ_THEME_STRIP_VISIBLE_COUNT = 6;

export const quizThemePresets: QuizThemePreset[] = [
  {
    id: "erg-classic",
    name: "ERG Classic",
    description: "Navy and red learning theme inspired by the ERG teacher workspace.",
    collection: "This Quiz",
    theme: {
      pageBackground: "#f8fafc",
      playerBackground: "#ffffff",
      canvasBorder: "#dbe5f1",
      headerBackground: "#0f6cbd",
      headerText: "#ffffff",
      accentStart: "#0f6cbd",
      accentEnd: "#cc0022",
      optionText: "#214f88",
      optionSelectedBackground: "#eaf1ff",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "#0f6cbd",
      sidebarActiveText: "#ffffff",
    },
  },
  {
    id: "harmony-mint",
    name: "Harmony Mint",
    description: "Fresh green gradients with a calm academic mood for daily practice quizzes.",
    collection: "Harmony",
    theme: {
      pageBackground: "#f4fbf5",
      playerBackground: "#fffef8",
      canvasBorder: "#c9dfc9",
      headerBackground: "#a7d29b",
      headerText: "#2f4f33",
      accentStart: "#7db587",
      accentEnd: "#c5d99a",
      optionText: "#45624b",
      optionSelectedBackground: "#edf6e8",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "#8bc69a",
      sidebarActiveText: "#294530",
    },
  },
  {
    id: "harmony-olive",
    name: "Harmony Olive",
    description: "Soft olive tones and warm paper surfaces for guided lesson content.",
    collection: "Harmony",
    theme: {
      pageBackground: "#fbfbef",
      playerBackground: "#fffef9",
      canvasBorder: "#dcd8ba",
      headerBackground: "#dfe6bf",
      headerText: "#4d5533",
      accentStart: "#b8c484",
      accentEnd: "#e6d9b2",
      optionText: "#4f5538",
      optionSelectedBackground: "#f7f5de",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "#d4ddb0",
      sidebarActiveText: "#4b5232",
    },
  },
  {
    id: "harmony-sky",
    name: "Harmony Sky",
    description: "Airy blue layers that keep the slide canvas bright and easy to scan.",
    collection: "Harmony",
    theme: {
      pageBackground: "#eff6ff",
      playerBackground: "#ffffff",
      canvasBorder: "#c7d8ea",
      headerBackground: "#c7d9f7",
      headerText: "#35537e",
      accentStart: "#8ab0eb",
      accentEnd: "#cfdcf8",
      optionText: "#3a567e",
      optionSelectedBackground: "#e7eefc",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "#b8cdf4",
      sidebarActiveText: "#37537a",
    },
  },
  {
    id: "harmony-cloud",
    name: "Harmony Cloud",
    description: "A slightly cooler blue preset for structured tests and review sessions.",
    collection: "Harmony",
    theme: {
      pageBackground: "#f5f8ff",
      playerBackground: "#ffffff",
      canvasBorder: "#d2dcf2",
      headerBackground: "#d8e4fb",
      headerText: "#42547a",
      accentStart: "#9ab8ef",
      accentEnd: "#dce6fa",
      optionText: "#44557b",
      optionSelectedBackground: "#edf3ff",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "#c7d8f7",
      sidebarActiveText: "#425279",
    },
  },
  {
    id: "harmony-coral",
    name: "Harmony Coral",
    description: "Warm coral highlights that feel energetic without overwhelming the slide.",
    collection: "Harmony",
    theme: {
      pageBackground: "#fff8f3",
      playerBackground: "#ffffff",
      canvasBorder: "#f3d3c4",
      headerBackground: "#ffd0b4",
      headerText: "#8a4f2d",
      accentStart: "#f6a77b",
      accentEnd: "#ffd2b7",
      optionText: "#8f5837",
      optionSelectedBackground: "#fff0e5",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "#ffc3a3",
      sidebarActiveText: "#8a4f2d",
    },
  },
  {
    id: "office-silver",
    name: "Office Silver",
    description: "Neutral metallic surfaces for internal training or process documentation.",
    collection: "Office",
    theme: {
      pageBackground: "#f7f8fa",
      playerBackground: "#ffffff",
      canvasBorder: "#d6dbe4",
      headerBackground: "#eef2f7",
      headerText: "#4c5563",
      accentStart: "#bac4d3",
      accentEnd: "#eceff5",
      optionText: "#505967",
      optionSelectedBackground: "#edf2f7",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "#dfe6ee",
      sidebarActiveText: "#4a5563",
    },
  },
  {
    id: "office-midnight",
    name: "Office Midnight",
    description: "Deep navy surfaces with clear white contrast for executive-style content.",
    collection: "Office",
    theme: {
      pageBackground: "#eef2f7",
      playerBackground: "#ffffff",
      canvasBorder: "#cbd5e1",
      headerBackground: "#1f2937",
      headerText: "#f8fafc",
      accentStart: "#0f172a",
      accentEnd: "#334155",
      optionText: "#1e293b",
      optionSelectedBackground: "#e2e8f0",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "#0f172a",
      sidebarActiveText: "#f8fafc",
    },
  },
  {
    id: "office-frost",
    name: "Office Frost",
    description: "Soft ice blue panels and pale neutrals for modern classroom dashboards.",
    collection: "Office",
    theme: {
      pageBackground: "#f1f7f9",
      playerBackground: "#ffffff",
      canvasBorder: "#c9d9dd",
      headerBackground: "#bdd2d7",
      headerText: "#37505b",
      accentStart: "#9bbbc2",
      accentEnd: "#dae9ec",
      optionText: "#425b66",
      optionSelectedBackground: "#e9f1f3",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "#b3ccd2",
      sidebarActiveText: "#36505a",
    },
  },
  {
    id: "office-paper",
    name: "Office Paper",
    description: "Cream paper tones with understated accents for policy and reading slides.",
    collection: "Office",
    theme: {
      pageBackground: "#fcf7f0",
      playerBackground: "#fffdfa",
      canvasBorder: "#e8dccd",
      headerBackground: "#efe4d6",
      headerText: "#6c5441",
      accentStart: "#d8c1a8",
      accentEnd: "#efe3d2",
      optionText: "#6e5643",
      optionSelectedBackground: "#f8efe3",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "#e9d9c6",
      sidebarActiveText: "#6a513e",
    },
  },
  {
    id: "kaleidoscope-confetti",
    name: "Kaleidoscope Confetti",
    description: "Playful peach and blue accents for younger learners or celebratory screens.",
    collection: "Kaleidoscope",
    theme: {
      pageBackground: "#fffaf0",
      playerBackground: "#ffffff",
      canvasBorder: "#f0dec4",
      headerBackground: "#ffe4b4",
      headerText: "#795433",
      accentStart: "#f4b35c",
      accentEnd: "#7ca8ff",
      optionText: "#6c553d",
      optionSelectedBackground: "#fff1d5",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "#ffd9a4",
      sidebarActiveText: "#76502f",
    },
  },
  {
    id: "kaleidoscope-prism",
    name: "Kaleidoscope Prism",
    description: "A brighter preset with balanced blues and apricot highlights for mixed media.",
    collection: "Kaleidoscope",
    theme: {
      pageBackground: "#fffdf7",
      playerBackground: "#ffffff",
      canvasBorder: "#d8dff5",
      headerBackground: "#f7d8b0",
      headerText: "#50506b",
      accentStart: "#87aefb",
      accentEnd: "#f6b474",
      optionText: "#52526d",
      optionSelectedBackground: "#eef4ff",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "#dfe8ff",
      sidebarActiveText: "#52536d",
    },
  },
  {
    id: "flow-mint",
    name: "Flow Mint",
    description: "Light mint ribbons with a gentle gradient for friendly lesson intros.",
    collection: "Flowing Lines",
    theme: {
      pageBackground: "#edfff4",
      playerBackground: "#ffffff",
      canvasBorder: "#bfe3cc",
      headerBackground: "#8fe1b4",
      headerText: "#2d5a43",
      accentStart: "#6ed099",
      accentEnd: "#b2ebcf",
      optionText: "#35614a",
      optionSelectedBackground: "#def9ea",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "#8ee0b0",
      sidebarActiveText: "#2d5a43",
    },
  },
  {
    id: "flow-ocean",
    name: "Flow Ocean",
    description: "Blue motion-inspired preset that keeps analytical quizzes feeling light.",
    collection: "Flowing Lines",
    theme: {
      pageBackground: "#eff7ff",
      playerBackground: "#ffffff",
      canvasBorder: "#bcd6f2",
      headerBackground: "#88b9ff",
      headerText: "#2e4e76",
      accentStart: "#6da4f2",
      accentEnd: "#bfd7ff",
      optionText: "#35547c",
      optionSelectedBackground: "#e6f0ff",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "#8eb8ff",
      sidebarActiveText: "#2d4d76",
    },
  },
  {
    id: "flow-violet",
    name: "Flow Violet",
    description: "Lavender movement and softer contrast for reflective learning content.",
    collection: "Flowing Lines",
    theme: {
      pageBackground: "#f6f0ff",
      playerBackground: "#ffffff",
      canvasBorder: "#d2c2ec",
      headerBackground: "#b295e5",
      headerText: "#4e4068",
      accentStart: "#9f7de0",
      accentEnd: "#ceb8f2",
      optionText: "#54466d",
      optionSelectedBackground: "#efe6ff",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "#ae90e0",
      sidebarActiveText: "#4e3f68",
    },
  },
  {
    id: "flow-rose",
    name: "Flow Rose",
    description: "Rose and blush gradients for softer storytelling or onboarding sequences.",
    collection: "Flowing Lines",
    theme: {
      pageBackground: "#fff2f6",
      playerBackground: "#ffffff",
      canvasBorder: "#edc3d0",
      headerBackground: "#e9a8be",
      headerText: "#6d4050",
      accentStart: "#d98aa5",
      accentEnd: "#efbfd0",
      optionText: "#714658",
      optionSelectedBackground: "#fde6ee",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "#e5a1b7",
      sidebarActiveText: "#6b4150",
    },
  },
  {
    id: "geometric-indigo",
    name: "Geometric Indigo",
    description: "Stronger dark indigo contrast for dramatic section breaks or scoring slides.",
    collection: "Geometric",
    theme: {
      pageBackground: "#eef3ff",
      playerBackground: "#ffffff",
      canvasBorder: "#b8c4ee",
      headerBackground: "#233a78",
      headerText: "#f8fbff",
      accentStart: "#274690",
      accentEnd: "#6da0ff",
      optionText: "#20345f",
      optionSelectedBackground: "#dde8ff",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "#233a78",
      sidebarActiveText: "#f8fbff",
    },
  },
  {
    id: "geometric-plum",
    name: "Geometric Plum",
    description: "Dark plum cards with richer accent pops for formal assessment recaps.",
    collection: "Geometric",
    theme: {
      pageBackground: "#f3eef9",
      playerBackground: "#ffffff",
      canvasBorder: "#c8bddb",
      headerBackground: "#4c2c6f",
      headerText: "#fbf8ff",
      accentStart: "#5d347f",
      accentEnd: "#a574d3",
      optionText: "#43295d",
      optionSelectedBackground: "#e8dcf6",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "#4d2d70",
      sidebarActiveText: "#fbf8ff",
    },
  },
  {
    id: "geometric-ruby",
    name: "Geometric Ruby",
    description: "A deeper red preset for checkpoints, outcomes, and decisive callouts.",
    collection: "Geometric",
    theme: {
      pageBackground: "#fdf1f3",
      playerBackground: "#ffffff",
      canvasBorder: "#e2bcc4",
      headerBackground: "#7d1732",
      headerText: "#fff7f9",
      accentStart: "#8f1d3c",
      accentEnd: "#d96889",
      optionText: "#6b1a30",
      optionSelectedBackground: "#fde3ea",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "#7e1833",
      sidebarActiveText: "#fff7f9",
    },
  },
  {
    id: "geometric-forest",
    name: "Geometric Forest",
    description: "Dark green blocks with bright accents for focused knowledge checks.",
    collection: "Geometric",
    theme: {
      pageBackground: "#eef8f1",
      playerBackground: "#ffffff",
      canvasBorder: "#bdd8c3",
      headerBackground: "#1d5b2a",
      headerText: "#f3fdf5",
      accentStart: "#247238",
      accentEnd: "#56b560",
      optionText: "#214d2c",
      optionSelectedBackground: "#dcf3df",
      inputBackground: "#ffffff",
      sidebarActiveBackground: "#205f2d",
      sidebarActiveText: "#f3fdf5",
    },
  },
];

export const defaultQuizTheme = quizThemePresets[0];

export const groupedQuizThemePresets = quizThemePresets.reduce<Record<string, QuizThemePreset[]>>((groups, preset) => {
  if (!groups[preset.collection]) {
    groups[preset.collection] = [];
  }

  groups[preset.collection].push(preset);
  return groups;
}, {});

export function getQuizThemePreset(themeId?: string) {
  return quizThemePresets.find((preset) => preset.id === themeId) ?? defaultQuizTheme;
}

export function resolveQuizTheme(themeId?: string, themeOverride?: Partial<Theme> | null): Theme {
  return {
    ...getQuizThemePreset(themeId).theme,
    ...(themeOverride ?? {}),
  };
}

export function getQuizThemeStyle(theme: Theme): CSSProperties {
  return {
    ["--quiz-page-bg" as string]: theme.pageBackground,
    ["--quiz-player-bg" as string]: theme.playerBackground,
    ["--quiz-canvas-border" as string]: theme.canvasBorder,
    ["--quiz-header-bg" as string]: theme.headerBackground,
    ["--quiz-header-text" as string]: theme.headerText,
    ["--quiz-accent-start" as string]: theme.accentStart,
    ["--quiz-accent-end" as string]: theme.accentEnd,
    ["--quiz-option-text" as string]: theme.optionText,
    ["--quiz-option-selected-bg" as string]: theme.optionSelectedBackground,
    ["--quiz-input-bg" as string]: theme.inputBackground,
    ["--quiz-sidebar-active-bg" as string]: theme.sidebarActiveBackground,
    ["--quiz-sidebar-active-text" as string]: theme.sidebarActiveText,
  } as CSSProperties;
}

export function getQuizThemeSwatchStyle(theme: Theme): CSSProperties {
  return {
    background: theme.pageBackground,
  };
}

export function getQuizThemeDeckStyle(themeId?: string): CSSProperties {
  const theme = getQuizThemePreset(themeId).theme;

  return {
    ["--classic-slide-bg" as string]: theme.playerBackground,
    ["--classic-slide-border" as string]: theme.canvasBorder,
    ["--classic-slide-text" as string]: theme.optionText,
    ["--classic-slide-choice-bg" as string]: theme.optionSelectedBackground,
    ["--classic-slide-choice-border" as string]: theme.canvasBorder,
    ["--classic-slide-card-bg" as string]: theme.playerBackground,
    ["--classic-slide-card-text" as string]: theme.optionText,
    ["--classic-slide-accent-gradient" as string]: theme.headerBackground,
    ["--classic-slide-accent-soft" as string]: theme.accentStart,
    ["--classic-slide-accent-strong" as string]: theme.accentEnd,
    ["--classic-slide-result-pass-bg" as string]: theme.accentStart,
    ["--classic-slide-result-fail-bg" as string]: theme.accentEnd,
    ["--classic-slide-result-copy" as string]: theme.optionText,
    ["--classic-slide-result-target-correct" as string]: theme.accentStart,
    ["--classic-slide-result-target-wrong" as string]: theme.accentEnd,
  } as CSSProperties;
}
