export const lcmsWorkspacePaths = [
  "schools",
  "schools/list",
  "schools/detail",
  "schools/overview",
  "schools/profile",
  "schools/academic-years",
  "schools/grades",
  "schools/classes",
  "schools/students",
  "schools/subjects",
  "schools/subject-enrollments",
  "schools/imports",
  "schools/reviews",
  "schools/reports",
  "schools/assessments",
  "schools/audit-log",
  "users",
  "questions",
  "quiz-bank",
  "quiz-editor",
  "rubrics",
  "session-templates",
  "report-templates",
  "legal",
  "settings",
  "customers",
  "center-tasks",
  "employees",
  "employees/face-detection",
  "employees/timesheet",
  "employees/teacher-absence",
  "report/dashboard-report",
  "report/crm-report",
  "report/student-report",
  "report/task-report",
  "report/cash-flow-report",
  "report/pnl-report",
  "report/sale-report",
  "setting/setting-center-feature",
  "setting/setting-center-role",
  "setting/promotions/price-discount-programs",
  "setting/promotions/vouchers",
  "setting/promotions/discounts",
  "setting/setting-center-task/task-status",
  "setting/setting-center-customer/customer-status",
  "setting/setting-class-room",
  "setting/setting-calendar-event",
  "setting/setting-criteria-score",
  "setting/setting-income-expense",
  "integration/setting-call-center",
  "integration/setting-zalo-account",
  "integration/setting-center-api-key",
] as const;

export const crmPaths = [
  "seo",
  "seo/schools",
  "seo/opportunities",
  "seo/pnl",
  "seo/follow-ups",
  "seo/handover",
] as const;

export const lmsPaths = [
  "home",
  "dashboard",
  "homework",
  "homework/assign",
  "homework/exercise-bank",
  "homework/progress",
  "homework/student-groups",
  "notifications",
  "account",
  "account/login-logs",
  "score",
  "attendance",
  "calendar",
  "class-log",
  "reports",
] as const;
