import type { ComponentType } from "react";
import AddIcon from "@mui/icons-material/Add";
import AddPhotoAlternateIcon from "@mui/icons-material/AddPhotoAlternate";
import ApartmentIcon from "@mui/icons-material/Apartment";
import ArticleIcon from "@mui/icons-material/Article";
import AssignmentIcon from "@mui/icons-material/Assignment";
import AssignmentTurnedInIcon from "@mui/icons-material/AssignmentTurnedIn";
import AudiotrackIcon from "@mui/icons-material/Audiotrack";
import AutoStoriesIcon from "@mui/icons-material/AutoStories";
import BarChartIcon from "@mui/icons-material/BarChart";
import BookmarkAddedIcon from "@mui/icons-material/BookmarkAdded";
import CalculateIcon from "@mui/icons-material/Calculate";
import CalendarMonthIcon from "@mui/icons-material/CalendarMonth";
import CheckIcon from "@mui/icons-material/Check";
import CheckCircleIconBase from "@mui/icons-material/CheckCircle";
import CheckCircleOutlinedIcon from "@mui/icons-material/CheckCircleOutlined";
import ChevronLeftIconBase from "@mui/icons-material/ChevronLeft";
import ChevronRightIconBase from "@mui/icons-material/ChevronRight";
import CloseIconBase from "@mui/icons-material/Close";
import CloudUploadIcon from "@mui/icons-material/CloudUpload";
import ContentCopyIconBase from "@mui/icons-material/ContentCopy";
import ContentCutIcon from "@mui/icons-material/ContentCut";
import ContentPasteIconBase from "@mui/icons-material/ContentPaste";
import CreateNewFolderIcon from "@mui/icons-material/CreateNewFolder";
import DeleteOutlinedIconBase from "@mui/icons-material/DeleteOutlined";
import DesktopWindowsIcon from "@mui/icons-material/DesktopWindows";
import DownloadIcon from "@mui/icons-material/Download";
import EditIcon from "@mui/icons-material/Edit";
import EmailOutlinedIcon from "@mui/icons-material/EmailOutlined";
import ErrorOutlineOutlinedIcon from "@mui/icons-material/ErrorOutlineOutlined";
import ExpandMoreIconBase from "@mui/icons-material/ExpandMore";
import ExploreIcon from "@mui/icons-material/Explore";
import FactCheckIcon from "@mui/icons-material/FactCheck";
import FolderIconBase from "@mui/icons-material/Folder";
import FormatAlignCenterIcon from "@mui/icons-material/FormatAlignCenter";
import FormatAlignJustifyIcon from "@mui/icons-material/FormatAlignJustify";
import FormatAlignLeftIcon from "@mui/icons-material/FormatAlignLeft";
import FormatAlignRightIcon from "@mui/icons-material/FormatAlignRight";
import FormatBoldIcon from "@mui/icons-material/FormatBold";
import FormatIndentDecreaseIcon from "@mui/icons-material/FormatIndentDecrease";
import FormatIndentIncreaseIcon from "@mui/icons-material/FormatIndentIncrease";
import FormatItalicIcon from "@mui/icons-material/FormatItalic";
import FormatListBulletedIcon from "@mui/icons-material/FormatListBulleted";
import FormatListNumberedIcon from "@mui/icons-material/FormatListNumbered";
import FormatSizeIconBase from "@mui/icons-material/FormatSize";
import FormatStrikethroughIcon from "@mui/icons-material/FormatStrikethrough";
import FormatUnderlinedIcon from "@mui/icons-material/FormatUnderlined";
import GppBadOutlinedIcon from "@mui/icons-material/GppBadOutlined";
import GroupsIcon from "@mui/icons-material/Groups";
import HeadphonesIcon from "@mui/icons-material/Headphones";
import HelpOutlineOutlinedIcon from "@mui/icons-material/HelpOutlineOutlined";
import HideImageOutlinedIcon from "@mui/icons-material/HideImageOutlined";
import HighlightOffIconBase from "@mui/icons-material/HighlightOff";
import ImageIconBase from "@mui/icons-material/Image";
import InsightsIcon from "@mui/icons-material/Insights";
import LayersIconBase from "@mui/icons-material/Layers";
import LinkIconBase from "@mui/icons-material/Link";
import LocalLibraryIcon from "@mui/icons-material/LocalLibrary";
import LockOutlinedIconBase from "@mui/icons-material/LockOutlined";
import LoopIcon from "@mui/icons-material/Loop";
import MoreHorizIcon from "@mui/icons-material/MoreHoriz";
import NorthEastIcon from "@mui/icons-material/NorthEast";
import OndemandVideoIcon from "@mui/icons-material/OndemandVideo";
import OpenInFullIcon from "@mui/icons-material/OpenInFull";
import PaletteOutlinedIcon from "@mui/icons-material/PaletteOutlined";
import PersonIcon from "@mui/icons-material/Person";
import PhoneIconBase from "@mui/icons-material/Phone";
import PlaceIcon from "@mui/icons-material/Place";
import PlayArrowIcon from "@mui/icons-material/PlayArrow";
import PublicIcon from "@mui/icons-material/Public";
import RateReviewOutlinedIcon from "@mui/icons-material/RateReviewOutlined";
import RefreshIcon from "@mui/icons-material/Refresh";
import RemoveIconBase from "@mui/icons-material/Remove";
import SaveIconBase from "@mui/icons-material/Save";
import SchoolIconBase from "@mui/icons-material/School";
import SearchIconBase from "@mui/icons-material/Search";
import SettingsOutlinedIconBase from "@mui/icons-material/SettingsOutlined";
import SlideshowIcon from "@mui/icons-material/Slideshow";
import SpellcheckIcon from "@mui/icons-material/Spellcheck";
import StarIconBase from "@mui/icons-material/Star";
import StickyNote2Icon from "@mui/icons-material/StickyNote2";
import SubscriptIconBase from "@mui/icons-material/Subscript";
import SuperscriptIconBase from "@mui/icons-material/Superscript";
import TableChartIcon from "@mui/icons-material/TableChart";
import TableRowsIcon from "@mui/icons-material/TableRows";
import TaskIcon from "@mui/icons-material/Task";
import TextFieldsIcon from "@mui/icons-material/TextFields";
import TuneIconBase from "@mui/icons-material/Tune";
import UploadIconBase from "@mui/icons-material/Upload";
import VerifiedUserIcon from "@mui/icons-material/VerifiedUser";
import VideocamIcon from "@mui/icons-material/Videocam";
import VisibilityIcon from "@mui/icons-material/Visibility";
import VpnKeyIcon from "@mui/icons-material/VpnKey";
import WarningAmberIcon from "@mui/icons-material/WarningAmber";
import ArrowDownwardIcon from "@mui/icons-material/ArrowDownward";
import ArrowForwardIcon from "@mui/icons-material/ArrowForward";
import ArrowUpwardIcon from "@mui/icons-material/ArrowUpward";
import AccountTreeIcon from "@mui/icons-material/AccountTree";
import type { SvgIconProps } from "@mui/material/SvgIcon";

export type MuiIconShimProps = Omit<SvgIconProps, "fontSize"> & {
  absoluteStrokeWidth?: boolean;
  size?: number | string;
  strokeWidth?: number | string;
};

export type LucideIcon = ComponentType<MuiIconShimProps>;

function createMuiIcon(Icon: ComponentType<SvgIconProps>): LucideIcon {
  return function MuiIconShim({ absoluteStrokeWidth, size, strokeWidth, sx, ...props }: MuiIconShimProps) {
    void absoluteStrokeWidth;
    void strokeWidth;

    const fontSize = typeof size === "number" ? `${size}px` : size;
    const sxValue = fontSize
      ? [{ fontSize }, ...(Array.isArray(sx) ? sx : sx ? [sx] : [])]
      : sx;

    return <Icon {...props} sx={sxValue} />;
  };
}

export const AlertCircle = createMuiIcon(ErrorOutlineOutlinedIcon);
export const AlertTriangle = createMuiIcon(WarningAmberIcon);
export const AlignCenter = createMuiIcon(FormatAlignCenterIcon);
export const AlignJustify = createMuiIcon(FormatAlignJustifyIcon);
export const AlignLeft = createMuiIcon(FormatAlignLeftIcon);
export const AlignRight = createMuiIcon(FormatAlignRightIcon);
export const ArrowDown = createMuiIcon(ArrowDownwardIcon);
export const ArrowRight = createMuiIcon(ArrowForwardIcon);
export const ArrowUp = createMuiIcon(ArrowUpwardIcon);
export const ArrowUpRight = createMuiIcon(NorthEastIcon);
export const BarChart3 = createMuiIcon(BarChartIcon);
export const Bold = createMuiIcon(FormatBoldIcon);
export const BookMarked = createMuiIcon(BookmarkAddedIcon);
export const BookOpen = createMuiIcon(AutoStoriesIcon);
export const BookOpenCheck = createMuiIcon(FactCheckIcon);
export const Building2 = createMuiIcon(ApartmentIcon);
export const Calculator = createMuiIcon(CalculateIcon);
export const CalendarDays = createMuiIcon(CalendarMonthIcon);
export const Check = createMuiIcon(CheckIcon);
export const CheckCircle = createMuiIcon(CheckCircleIconBase);
export const CheckCircle2 = createMuiIcon(CheckCircleOutlinedIcon);
export const ChevronDown = createMuiIcon(ExpandMoreIconBase);
export const ChevronLeft = createMuiIcon(ChevronLeftIconBase);
export const ChevronRight = createMuiIcon(ChevronRightIconBase);
export const Clipboard = createMuiIcon(ContentPasteIconBase);
export const ClipboardCheck = createMuiIcon(AssignmentTurnedInIcon);
export const ClipboardList = createMuiIcon(AssignmentIcon);
export const Compass = createMuiIcon(ExploreIcon);
export const Copy = createMuiIcon(ContentCopyIconBase);
export const Download = createMuiIcon(DownloadIcon);
export const Eye = createMuiIcon(VisibilityIcon);
export const FileCheck = createMuiIcon(TaskIcon);
export const FileQuestion = createMuiIcon(HelpOutlineOutlinedIcon);
export const FileSpreadsheet = createMuiIcon(TableChartIcon);
export const FileText = createMuiIcon(ArticleIcon);
export const Folder = createMuiIcon(FolderIconBase);
export const FolderPlus = createMuiIcon(CreateNewFolderIcon);
export const GitBranch = createMuiIcon(AccountTreeIcon);
export const Globe = createMuiIcon(PublicIcon);
export const GraduationCap = createMuiIcon(SchoolIconBase);
export const Heading = createMuiIcon(FormatSizeIconBase);
export const Headphones = createMuiIcon(HeadphonesIcon);
export const HelpCircle = createMuiIcon(HelpOutlineOutlinedIcon);
export const Image = createMuiIcon(ImageIconBase);
export const ImageOff = createMuiIcon(HideImageOutlinedIcon);
export const ImagePlus = createMuiIcon(AddPhotoAlternateIcon);
export const Indent = createMuiIcon(FormatIndentIncreaseIcon);
export const Italic = createMuiIcon(FormatItalicIcon);
export const KeyRound = createMuiIcon(VpnKeyIcon);
export const Layers = createMuiIcon(LayersIconBase);
export const Layers3 = createMuiIcon(LayersIconBase);
export const LibraryBig = createMuiIcon(LocalLibraryIcon);
export const LineChart = createMuiIcon(InsightsIcon);
export const Link = createMuiIcon(LinkIconBase);
export const List = createMuiIcon(FormatListBulletedIcon);
export const ListOrdered = createMuiIcon(FormatListNumberedIcon);
export const ListTree = createMuiIcon(AccountTreeIcon);
export const Loader2 = createMuiIcon(LoopIcon);
export const Lock = createMuiIcon(LockOutlinedIconBase);
export const Mail = createMuiIcon(EmailOutlinedIcon);
export const MapPin = createMuiIcon(PlaceIcon);
export const Maximize2 = createMuiIcon(OpenInFullIcon);
export const Minus = createMuiIcon(RemoveIconBase);
export const Monitor = createMuiIcon(DesktopWindowsIcon);
export const MonitorPlay = createMuiIcon(OndemandVideoIcon);
export const MoreHorizontal = createMuiIcon(MoreHorizIcon);
export const Music = createMuiIcon(AudiotrackIcon);
export const Outdent = createMuiIcon(FormatIndentDecreaseIcon);
export const Palette = createMuiIcon(PaletteOutlinedIcon);
export const Pencil = createMuiIcon(EditIcon);
export const Phone = createMuiIcon(PhoneIconBase);
export const Play = createMuiIcon(PlayArrowIcon);
export const Plus = createMuiIcon(AddIcon);
export const Presentation = createMuiIcon(SlideshowIcon);
export const RefreshCw = createMuiIcon(RefreshIcon);
export const Save = createMuiIcon(SaveIconBase);
export const School = createMuiIcon(SchoolIconBase);
export const Scissors = createMuiIcon(ContentCutIcon);
export const Search = createMuiIcon(SearchIconBase);
export const Settings = createMuiIcon(SettingsOutlinedIconBase);
export const Settings2 = createMuiIcon(TuneIconBase);
export const ShieldAlert = createMuiIcon(GppBadOutlinedIcon);
export const ShieldCheck = createMuiIcon(VerifiedUserIcon);
export const Sliders = createMuiIcon(TuneIconBase);
export const SpellCheck = createMuiIcon(SpellcheckIcon);
export const SquarePen = createMuiIcon(RateReviewOutlinedIcon);
export const Star = createMuiIcon(StarIconBase);
export const StickyNote = createMuiIcon(StickyNote2Icon);
export const Strikethrough = createMuiIcon(FormatStrikethroughIcon);
export const Subscript = createMuiIcon(SubscriptIconBase);
export const Superscript = createMuiIcon(SuperscriptIconBase);
export const Table = createMuiIcon(TableRowsIcon);
export const Trash2 = createMuiIcon(DeleteOutlinedIconBase);
export const Type = createMuiIcon(TextFieldsIcon);
export const Underline = createMuiIcon(FormatUnderlinedIcon);
export const Upload = createMuiIcon(UploadIconBase);
export const UploadCloud = createMuiIcon(CloudUploadIcon);
export const User = createMuiIcon(PersonIcon);
export const UsersRound = createMuiIcon(GroupsIcon);
export const Video = createMuiIcon(VideocamIcon);
export const X = createMuiIcon(CloseIconBase);
export const XCircle = createMuiIcon(HighlightOffIconBase);
