export type StudentCopy = typeof enCopy;

export const viCopy = {
  badge: "Học sinh & bài tập",
  description:
    "Một màn duy nhất để giáo viên xem danh sách học sinh, lọc nhóm cần xử lý, chọn học sinh và giao bài ngay. Thiết kế ưu tiên thao tác đơn giản cho giáo viên không rành công nghệ.",
  openReports: "Xem báo cáo",
  listTitle: "Danh sách học sinh",
  listDescription: (count: number, support: number): string =>
    `${count} học sinh đang hiển thị, ${support} em cần hỗ trợ.`,
  searchPlaceholder: "Tìm học sinh, bài đang làm, ghi chú...",
  classFilter: "Lọc theo lớp",
  subjectFilter: "Lọc theo môn",
  statusFilter: "Lọc theo trạng thái",
  progressFilter: "Lọc theo tiến độ",
  allSubjects: "Tất cả môn",
  allStatuses: "Tất cả trạng thái",
  allProgress: "Tất cả tiến độ",
  selectSupport: "Chọn nhóm cần hỗ trợ",
  selectionSummary: (count: number): string => `${count} học sinh đã chọn.`,
  visibleSummary: (count: number): string => `${count} học sinh trong danh sách lọc.`,
  openAssignDialog: (count: number): string => (count > 0 ? `Giao bài cho ${count} học sinh` : "Chọn học sinh để giao bài"),
  selectVisible: "Chọn tất cả đang lọc",
  unselectVisible: "Bỏ chọn đang lọc",
  clearSelection: "Bỏ chọn",
  pickColumn: "Chọn",
  studentColumn: "Học sinh",
  assignmentColumn: "Bài đang làm",
  progressColumn: "Tiến độ",
  scoreColumn: "Điểm",
  statusColumn: "Trạng thái",
  actionColumn: "Chi tiết",
  selectStudent: (name: string): string => `Chọn ${name}`,
  viewDetail: "Xem",
  emptyTitle: "Không có học sinh phù hợp",
  emptyDescription: "Thử đổi bộ lọc hoặc tìm theo tên học sinh khác.",
  status: {
    ahead: "Bứt tốc",
    steady: "Ổn định",
    support: "Cần hỗ trợ",
  },
  progress: {
    notStarted: "Chưa bắt đầu",
    inProgress: "Đang làm",
    completed: "Đã hoàn thành",
  },
  assignPanelTitle: "Giao bài",
  assignDialogTitle: "Chọn bài tập để giao",
  assignDialogDescription: "Chọn môn, level, rồi chọn bài theo từng chủ đề. Chủ đề chưa phân loại sẽ nằm trong nhóm Khác.",
  assignPanelDescription: (count: number): string =>
    count > 0 ? `Sẵn sàng giao bài cho ${count} học sinh đã chọn.` : "Tick học sinh trong bảng để bắt đầu giao bài.",
  closeDialog: "Đóng cửa sổ giao bài",
  selectedStudentsTitle: "Học sinh nhận bài",
  noStudentSelected: "Chưa chọn học sinh nào.",
  selectedRecipientsTitle: "Danh sách học sinh nhận bài",
  selectedRecipientsCount: (count: number): string => `${count} học sinh`,
  subjectPickerLabel: "Môn học",
  levelPickerLabel: "Level",
  assignmentListTitle: "Danh sách bài theo chủ đề",
  assignmentListDescription: "Chọn một bài train hoặc test trong các chủ đề bên dưới.",
  assignmentLabel: "Bài tập",
  assignmentPathLabel: "Lộ trình IC3 GS6",
  topicLabel: "Chủ đề",
  activityTypeLabel: "Loại bài",
  trainType: "Train",
  trainTypeDescription: "Luyện tập có hướng dẫn",
  testType: "Test",
  testTypeDescription: "Kiểm tra/chấm điểm",
  assignmentChoiceLabel: "Chọn bài cụ thể",
  selectedActivityLabel: "Bài đã chọn",
  selectedActivitiesLabel: "Bài đã chọn",
  selectedAssignmentsCount: (count: number): string => `${count} bài tập đã chọn`,
  noAssignmentSelectedTitle: "Chưa chọn bài tập",
  noAssignmentSelectedDescription: "Chọn một hoặc nhiều bài tập trong danh sách theo chủ đề.",
  questionCountValue: (count: number): string => `${count} câu`,
  durationLabel: "Thời lượng",
  dueDateLabel: "Hạn nộp",
  noteLabel: "Ghi chú cho học sinh",
  notePlaceholder: "Ví dụ: Làm phần luyện tập 1-3 trước 20:30...",
  cancelAction: "Hủy",
  otherTopicLabel: "Khác",
  topicCount: (count: number): string => `${count} bài`,
  deliveryBatchTitle: (count: number, firstTitle: string): string => `${count} bài đã chọn: ${firstTitle}`,
  deliveryHint: (count: number, schoolName: string): string =>
    count > 0 ? `Bài sẽ được giao cho ${count} học sinh tại ${schoolName}.` : "Nút giao bài sẽ mở sau khi chọn học sinh.",
  deliverAction: (count: number): string => (count > 0 ? `Giao bài cho ${count} học sinh` : "Chọn học sinh để giao bài"),
  recentTitle: "Đã giao gần đây",
  recentDescription: "Các lượt giao bài mới nhất để giáo viên kiểm tra lại nhanh.",
  studentUnit: (): string => "học sinh",
  submittedLabel: "Đã nộp",
  inProgressLabel: "Đang làm",
  reviewLabel: "Chờ chấm",
  studentPanelTitle: "Hồ sơ nhanh",
  studentPanelDescription: "Xem nhanh tình hình một học sinh mà không rời khỏi bảng.",
  progressLabel: "Tiến độ",
  scoreLabel: "Điểm TB",
  scoreUnit: "điểm",
  streakLabel: "Chuỗi ngày",
  completedLabel: "Đã xong",
  currentAssignmentTitle: "Bài hiện tại",
  mentorNoteTitle: "Gợi ý cho giáo viên",
  sampleAssignment: "Ôn tập phân số và quy đồng",
};

export const enCopy = {
  badge: "Students & assignments",
  description:
    "One simple workspace for teachers to review the roster, filter the right group, select students, and assign work immediately.",
  openReports: "View reports",
  listTitle: "Student list",
  listDescription: (count: number, support: number): string =>
    `${count} ${count === 1 ? "student" : "students"} shown, ${support} need support.`,
  searchPlaceholder: "Search student, live assignment, note...",
  classFilter: "Filter by class",
  subjectFilter: "Filter by subject",
  statusFilter: "Filter by status",
  progressFilter: "Filter by progress",
  allSubjects: "All subjects",
  allStatuses: "All statuses",
  allProgress: "All progress",
  selectSupport: "Select support group",
  selectionSummary: (count: number): string => `${count} ${count === 1 ? "student" : "students"} selected.`,
  visibleSummary: (count: number): string => `${count} ${count === 1 ? "student" : "students"} in the filtered list.`,
  openAssignDialog: (count: number): string =>
    count > 0 ? `Assign to ${count} ${count === 1 ? "student" : "students"}` : "Select students to assign",
  selectVisible: "Select all filtered",
  unselectVisible: "Unselect filtered",
  clearSelection: "Clear",
  pickColumn: "Pick",
  studentColumn: "Student",
  assignmentColumn: "Current work",
  progressColumn: "Progress",
  scoreColumn: "Score",
  statusColumn: "Status",
  actionColumn: "Details",
  selectStudent: (name: string): string => `Select ${name}`,
  viewDetail: "View",
  emptyTitle: "No matching students",
  emptyDescription: "Try changing the filters or searching another name.",
  status: {
    ahead: "Ahead",
    steady: "Steady",
    support: "Support",
  },
  progress: {
    notStarted: "Not started",
    inProgress: "In progress",
    completed: "Completed",
  },
  assignPanelTitle: "Assign work",
  assignDialogTitle: "Choose assignment",
  assignDialogDescription: "Choose a subject and level, then pick an activity grouped by topic. Ungrouped work appears under Other.",
  assignPanelDescription: (count: number): string =>
    count > 0
      ? `Ready to assign work to ${count} selected ${count === 1 ? "student" : "students"}.`
      : "Tick students in the table to start assigning work.",
  closeDialog: "Close assignment dialog",
  selectedStudentsTitle: "Recipients",
  noStudentSelected: "No students selected yet.",
  selectedRecipientsTitle: "Selected recipients",
  selectedRecipientsCount: (count: number): string => `${count} ${count === 1 ? "student" : "students"}`,
  subjectPickerLabel: "Subject",
  levelPickerLabel: "Level",
  assignmentListTitle: "Activities by topic",
  assignmentListDescription: "Pick one train or test activity from the topic groups below.",
  assignmentLabel: "Assignment",
  assignmentPathLabel: "IC3 GS6 path",
  topicLabel: "Topic",
  activityTypeLabel: "Activity type",
  trainType: "Train",
  trainTypeDescription: "Guided practice",
  testType: "Test",
  testTypeDescription: "Graded check",
  assignmentChoiceLabel: "Choose activity",
  selectedActivityLabel: "Selected activity",
  selectedActivitiesLabel: "Selected activities",
  selectedAssignmentsCount: (count: number): string => `${count} selected ${count === 1 ? "activity" : "activities"}`,
  noAssignmentSelectedTitle: "No assignment selected",
  noAssignmentSelectedDescription: "Choose one or more activities from the topic list.",
  questionCountValue: (count: number): string => `${count} ${count === 1 ? "question" : "questions"}`,
  durationLabel: "Duration",
  dueDateLabel: "Due date",
  noteLabel: "Student note",
  notePlaceholder: "Example: Complete practice 1-3 before 20:30...",
  cancelAction: "Cancel",
  otherTopicLabel: "Other",
  topicCount: (count: number): string => `${count} ${count === 1 ? "activity" : "activities"}`,
  deliveryBatchTitle: (count: number, firstTitle: string): string => `${count} selected activities: ${firstTitle}`,
  deliveryHint: (count: number, schoolName: string): string =>
    count > 0
      ? `This work will be delivered to ${count} ${count === 1 ? "student" : "students"} at ${schoolName}.`
      : "Assign button unlocks after selecting students.",
  deliverAction: (count: number): string =>
    count > 0 ? `Assign to ${count} ${count === 1 ? "student" : "students"}` : "Select students to assign",
  recentTitle: "Recently assigned",
  recentDescription: "Recent delivery batches so teachers can quickly verify what was sent.",
  studentUnit: (count: number): string => (count === 1 ? "student" : "students"),
  submittedLabel: "Submitted",
  inProgressLabel: "In progress",
  reviewLabel: "To review",
  studentPanelTitle: "Quick profile",
  studentPanelDescription: "Review one learner without leaving the table.",
  progressLabel: "Progress",
  scoreLabel: "Avg score",
  scoreUnit: "pts",
  streakLabel: "Streak",
  completedLabel: "Completed",
  currentAssignmentTitle: "Current assignment",
  mentorNoteTitle: "Teacher recommendation",
  sampleAssignment: "Fraction review and common denominators",
};
