import type {
  StudentDashboardAssignment,
  StudentDashboardProfile,
  StudentDiscussionThread,
  StudentTeacherAnnouncement,
} from "@/features/elearning/student-dashboard/types/student-dashboard-types";
import { sampleQuiz } from "@/lib/sample-quiz";

export const studentDashboardProfile: StudentDashboardProfile = {
  id: "student-current",
  name: "Võ Ngọc Linh",
  className: "Lớp 6A1",
  gradeLabel: "Khối 6",
  schoolName: "ERG Alpha Campus",
  homeroomTeacher: "Ngọc Anh",
  averageScore: 91,
  completedAssignments: 18,
  totalAssignments: 24,
  motivationPoints: 1240,
  weeklyGoalProgress: 78,
};

export const studentAssignments: StudentDashboardAssignment[] = [
  {
    id: "assignment-active",
    quizId: sampleQuiz.id,
    title: sampleQuiz.title,
    subtitle: "Ôn tập kỹ năng tương tác cốt lõi",
    subjectLabel: "Tin học",
    teacherName: "Nguyễn Phát Tài",
    status: "in_progress",
    progressRate: 67,
    answeredCount: 4,
    totalQuestions: 6,
    score: null,
    maxScore: 60,
    dueLabel: "Hạn nộp hôm nay, 20:30",
    statusLabel: "Đang làm",
    lastActivityLabel: "Hoạt động 12 phút trước",
    focusNote: "Bạn đang đi đúng nhịp, chỉ còn 2 câu nữa để hoàn thành bài.",
    attempts: [
      {
        id: "attempt-active-3",
        score: 22,
        maxScore: 60,
        completedAtLabel: "Hôm nay, 19:42",
        durationLabel: "18 phút",
      },
      {
        id: "attempt-active-2",
        score: 20,
        maxScore: 60,
        completedAtLabel: "Hôm nay, 18:10",
        durationLabel: "16 phút",
      },
      {
        id: "attempt-active-1",
        score: 17,
        maxScore: 60,
        completedAtLabel: "Hôm qua, 20:14",
        durationLabel: "21 phút",
      },
    ],
  },
  {
    id: "assignment-english",
    quizId: sampleQuiz.id,
    title: "Reading Sprint - Daily Routines",
    subtitle: "Đọc hiểu và chọn đáp án nhanh",
    subjectLabel: "Tiếng Anh",
    teacherName: "Trần Thu Hà",
    status: "not_started",
    progressRate: 0,
    answeredCount: 0,
    totalQuestions: 10,
    score: null,
    maxScore: 100,
    dueLabel: "Hạn nộp ngày mai, 09:00",
    statusLabel: "Chưa bắt đầu",
    lastActivityLabel: "Mới được giao 2 giờ trước",
    focusNote: "Ưu tiên làm trước 21:00 để giữ chuỗi hoàn thành trong tuần.",
    attempts: [],
  },
  {
    id: "assignment-math",
    quizId: sampleQuiz.id,
    title: "Luyện phân số và quy đồng",
    subtitle: "Bài tập về nhà tuần 4",
    subjectLabel: "Toán học",
    teacherName: "Lê Thị Mỹ Duyên",
    status: "submitted",
    progressRate: 100,
    answeredCount: 12,
    totalQuestions: 12,
    score: 94,
    maxScore: 100,
    dueLabel: "Đã nộp đúng hạn",
    statusLabel: "Đã nộp",
    lastActivityLabel: "Nộp hôm qua, 21:04",
    focusNote: "Điểm rất tốt, chỉ cần rà lại 1 câu vận dụng cuối.",
    attempts: [
      {
        id: "attempt-math-4",
        score: 94,
        maxScore: 100,
        completedAtLabel: "Hôm qua, 21:04",
        durationLabel: "24 phút",
      },
      {
        id: "attempt-math-3",
        score: 88,
        maxScore: 100,
        completedAtLabel: "Hôm qua, 20:25",
        durationLabel: "27 phút",
      },
      {
        id: "attempt-math-2",
        score: 81,
        maxScore: 100,
        completedAtLabel: "Thứ ba, 19:12",
        durationLabel: "31 phút",
      },
      {
        id: "attempt-math-1",
        score: 76,
        maxScore: 100,
        completedAtLabel: "Thứ hai, 20:01",
        durationLabel: "34 phút",
      },
    ],
  },
  {
    id: "assignment-science",
    quizId: sampleQuiz.id,
    title: "Khoa học - Lực ma sát",
    subtitle: "Tự luận ngắn kết hợp trắc nghiệm",
    subjectLabel: "Khoa học",
    teacherName: "Phạm Gia Bảo",
    status: "overdue",
    progressRate: 35,
    answeredCount: 3,
    totalQuestions: 8,
    score: null,
    maxScore: 80,
    dueLabel: "Quá hạn 1 ngày",
    statusLabel: "Quá hạn",
    lastActivityLabel: "Dừng lại từ hôm qua, 18:15",
    focusNote: "Cần hoàn tất sớm để không mất điểm thi đua tuần.",
    attempts: [
      {
        id: "attempt-science-2",
        score: 46,
        maxScore: 80,
        completedAtLabel: "Hôm qua, 18:15",
        durationLabel: "22 phút",
      },
      {
        id: "attempt-science-1",
        score: 39,
        maxScore: 80,
        completedAtLabel: "Thứ ba, 17:40",
        durationLabel: "19 phút",
      },
    ],
  },
];

export const studentDiscussionThreads: StudentDiscussionThread[] = [
  {
    id: "discussion-drag-drop",
    title: "Mọi người giải thích giúp mình câu kéo-thả trong GS6 LV3?",
    content:
      "Mình hiểu ý tưởng chung nhưng vẫn nhầm khi ghép thao tác với kết quả. Bạn nào làm rồi chỉ mình cách đọc đề nhanh hơn được không?",
    authorName: "Võ Ngọc Linh",
    authorInitials: "VL",
    createdAtLabel: "Hôm nay, 19:50",
    createdAtMs: 4000,
    className: "Lớp 6A1",
    relatedAssignmentTitle: "GS6 LV3 OTTHBS (TRAINING)",
    isResolved: false,
    attachments: [],
    replies: [
      {
        id: "reply-drag-drop-1",
        authorName: "Nguyễn Minh Khôi",
        authorInitials: "NK",
        createdAtLabel: "Hôm nay, 20:02",
        createdAtMs: 5000,
        content: "Mình làm bằng cách gạch chân từ khóa trước, ví dụ thao tác nào có chữ kéo thì tìm phần mô tả di chuyển đối tượng.",
        attachments: [],
      },
      {
        id: "reply-drag-drop-2",
        authorName: "Lê Gia Hân",
        authorInitials: "LH",
        createdAtLabel: "Hôm nay, 20:08",
        createdAtMs: 6000,
        content: "Nếu còn rối thì mở lại câu ví dụ trong bài trước, nó giống gần như cùng một dạng đó.",
        attachments: [],
      },
    ],
  },
  {
    id: "discussion-fraction",
    title: "Bài phân số: quy đồng mẫu số bước cuối làm thế nào?",
    content:
      "Mình tìm được mẫu chung rồi nhưng bước nhân tử phụ hay bị sai. Có bạn nào có cách kiểm tra lại nhanh không?",
    authorName: "Trần Bảo",
    authorInitials: "TB",
    createdAtLabel: "Hôm qua, 21:18",
    createdAtMs: 2000,
    className: "Lớp 6A1",
    relatedAssignmentTitle: "Luyện phân số và quy đồng",
    isResolved: true,
    attachments: [],
    replies: [
      {
        id: "reply-fraction-1",
        authorName: "Võ Ngọc Linh",
        authorInitials: "VL",
        createdAtLabel: "Hôm qua, 21:25",
        createdAtMs: 2500,
        content: "Bạn lấy mẫu chung chia mẫu cũ trước, kết quả đó nhân cả tử và mẫu. Làm xong thử rút gọn lại để kiểm tra.",
        attachments: [],
      },
      {
        id: "reply-fraction-2",
        authorName: "Lê Gia Hân",
        authorInitials: "LH",
        createdAtLabel: "Hôm qua, 21:31",
        createdAtMs: 3000,
        content: "Mình thường viết tử phụ ở phía trên mẫu cũ để không quên nhân tử số.",
        attachments: [],
      },
    ],
  },
  {
    id: "discussion-friction",
    title: "Khoa học lực ma sát: lấy ví dụ thực tế nào dễ nhớ?",
    content:
      "Mai mình cần trả lời câu tự luận ngắn. Mình đang nghĩ tới phanh xe đạp nhưng chưa biết diễn đạt cho đủ ý.",
    authorName: "Phan Phúc",
    authorInitials: "PP",
    createdAtLabel: "Thứ ba, 18:40",
    createdAtMs: 1000,
    className: "Lớp 6A1",
    relatedAssignmentTitle: "Khoa học - Lực ma sát",
    isResolved: false,
    attachments: [],
    replies: [
      {
        id: "reply-friction-1",
        authorName: "Nguyễn Minh Khôi",
        authorInitials: "NK",
        createdAtLabel: "Thứ ba, 18:51",
        createdAtMs: 1500,
        content: "Phanh xe đạp ổn đó. Má phanh ép vào bánh tạo ma sát, làm bánh quay chậm lại và xe dừng.",
        attachments: [],
      },
    ],
  },
];

export const studentTeacherAnnouncements: StudentTeacherAnnouncement[] = [
  {
    id: "announcement-weekly-plan",
    title: "Lịch học và bài ưu tiên tuần này",
    content:
      "Lớp 6A1 hoàn thành GS6 LV3 trước 20:30 hôm nay. Những bạn chưa làm bài Reading Sprint cần bắt đầu trước tối mai để kịp tiến độ.",
    teacherName: "Nguyễn Phát Tài",
    targetLabel: "Lớp 6A1",
    createdAtLabel: "Hôm nay, 08:15",
    isPinned: true,
  },
  {
    id: "announcement-materials",
    title: "Tài liệu ôn tập IC3 Spark",
    content:
      "Thầy đã cập nhật bộ câu hỏi luyện tập mới. Các em đọc kỹ phần thao tác kéo-thả và ghi lại câu hỏi trong tab Thảo luận nếu còn vướng.",
    teacherName: "Nguyễn Phát Tài",
    targetLabel: "Lớp 6A1",
    createdAtLabel: "Hôm qua, 17:30",
  },
  {
    id: "announcement-reminder",
    title: "Nhắc nộp bài Toán học",
    content:
      "Các bạn đã làm bài phân số có thể xem lại kết quả trong tab Điểm bài tập. Bạn nào chưa chắc phần quy đồng mẫu số hãy hỏi cô ở buổi học tới.",
    teacherName: "Lê Thị Mỹ Duyên",
    targetLabel: "Võ Ngọc Linh",
    createdAtLabel: "Thứ ba, 19:10",
  },
];
