import type {
  AssignmentRun,
  ClassroomClusterId,
  ClassroomSchool,
  ClassroomSnapshot,
  ClassroomStudent,
  InterventionItem,
  LeaderboardEntry,
  LeaderboardScope,
  LearnerJourney,
  StudentStatus,
} from "@/features/lms/classroom/types/classroom-types";

export const classroomClusters: Array<{ id: ClassroomClusterId; label: string }> = [
  { id: "central", label: "Cụm Trung tâm" },
  { id: "east", label: "Cụm Đông Bắc" },
  { id: "south", label: "Cụm Nam Sài Gòn" },
];

export const classroomSchools: ClassroomSchool[] = [
  {
    id: "school-erg-alpha",
    name: "ERG Alpha Campus",
    clusterId: "central",
    principal: "Trần Mai Phương",
    activeStudents: 486,
    activeClasses: 14,
    completionRate: 87,
    averageScore: 84,
    overdueAssignments: 18,
    flaggedStudents: 27,
  },
  {
    id: "school-erg-east",
    name: "ERG East Learning Point",
    clusterId: "east",
    principal: "Nguyễn Hải Đăng",
    activeStudents: 352,
    activeClasses: 11,
    completionRate: 81,
    averageScore: 79,
    overdueAssignments: 21,
    flaggedStudents: 33,
  },
  {
    id: "school-erg-south",
    name: "ERG South Studio",
    clusterId: "south",
    principal: "Lê Thùy Nhi",
    activeStudents: 294,
    activeClasses: 9,
    completionRate: 84,
    averageScore: 82,
    overdueAssignments: 12,
    flaggedStudents: 19,
  },
];

export const classroomSnapshots: ClassroomSnapshot[] = [
  {
    id: "class-6a1",
    schoolId: "school-erg-alpha",
    schoolName: "ERG Alpha Campus",
    clusterId: "central",
    className: "Lớp 6A1",
    gradeLabel: "Khối 6",
    homeroomTeacher: "Ngọc Anh",
    studentCount: 50,
    activeAssignments: 4,
    completionRate: 91,
    averageScore: 86,
    riskStudents: 3,
    competitionPoints: 1_280,
    lastSubmissionAt: "12 phút trước",
  },
  {
    id: "class-6a2",
    schoolId: "school-erg-alpha",
    schoolName: "ERG Alpha Campus",
    clusterId: "central",
    className: "Lớp 6A2",
    gradeLabel: "Khối 6",
    homeroomTeacher: "Tú Uyên",
    studentCount: 29,
    activeAssignments: 3,
    completionRate: 84,
    averageScore: 80,
    riskStudents: 5,
    competitionPoints: 1_130,
    lastSubmissionAt: "34 phút trước",
  },
  {
    id: "class-7b1",
    schoolId: "school-erg-alpha",
    schoolName: "ERG Alpha Campus",
    clusterId: "central",
    className: "Lớp 7B1",
    gradeLabel: "Khối 7",
    homeroomTeacher: "Khánh Vy",
    studentCount: 31,
    activeAssignments: 4,
    completionRate: 88,
    averageScore: 85,
    riskStudents: 4,
    competitionPoints: 1_240,
    lastSubmissionAt: "8 phút trước",
  },
  {
    id: "class-7c2",
    schoolId: "school-erg-east",
    schoolName: "ERG East Learning Point",
    clusterId: "east",
    className: "Lớp 7C2",
    gradeLabel: "Khối 7",
    homeroomTeacher: "Bích Hà",
    studentCount: 30,
    activeAssignments: 5,
    completionRate: 77,
    averageScore: 74,
    riskStudents: 7,
    competitionPoints: 1_020,
    lastSubmissionAt: "41 phút trước",
  },
  {
    id: "class-8d1",
    schoolId: "school-erg-east",
    schoolName: "ERG East Learning Point",
    clusterId: "east",
    className: "Lớp 8D1",
    gradeLabel: "Khối 8",
    homeroomTeacher: "Nguyễn Minh Tâm",
    studentCount: 28,
    activeAssignments: 4,
    completionRate: 79,
    averageScore: 77,
    riskStudents: 6,
    competitionPoints: 1_075,
    lastSubmissionAt: "21 phút trước",
  },
  {
    id: "class-6m1",
    schoolId: "school-erg-south",
    schoolName: "ERG South Studio",
    clusterId: "south",
    className: "Lớp 6M1",
    gradeLabel: "Khối 6",
    homeroomTeacher: "Phạm Mỹ Duyên",
    studentCount: 27,
    activeAssignments: 3,
    completionRate: 86,
    averageScore: 83,
    riskStudents: 2,
    competitionPoints: 1_190,
    lastSubmissionAt: "17 phút trước",
  },
];

export const assignmentRuns: AssignmentRun[] = [
  {
    id: "assignment-fractions",
    title: "Ôn tập phân số và quy đồng",
    subjectLabel: "Toán học",
    targetLevel: "Khối 6",
    activeClasses: 6,
    completionRate: 83,
    submittedCount: 142,
    inProgressCount: 38,
    needsReviewCount: 11,
    dueLabel: "Hạn nộp hôm nay, 20:30",
  },
  {
    id: "assignment-reading",
    title: "Reading sprint - daily routines",
    subjectLabel: "Tiếng Anh",
    targetLevel: "Khối 6",
    activeClasses: 5,
    completionRate: 89,
    submittedCount: 151,
    inProgressCount: 24,
    needsReviewCount: 8,
    dueLabel: "Hạn nộp ngày mai, 09:00",
  },
  {
    id: "assignment-spreadsheets",
    title: "Bảng tính - hàm SUM và AVERAGE",
    subjectLabel: "Tin học",
    targetLevel: "Khối 7",
    activeClasses: 4,
    completionRate: 76,
    submittedCount: 88,
    inProgressCount: 31,
    needsReviewCount: 19,
    dueLabel: "Hạn nộp ngày mai, 16:30",
  },
  {
    id: "assignment-friction",
    title: "Vật lý - lực ma sát trong đời sống",
    subjectLabel: "Khoa học",
    targetLevel: "Khối 8",
    activeClasses: 3,
    completionRate: 71,
    submittedCount: 52,
    inProgressCount: 18,
    needsReviewCount: 13,
    dueLabel: "Hạn nộp sau 2 ngày",
  },
];

const baseClassroomStudents: ClassroomStudent[] = [
  {
    id: "student-ngoc-linh",
    name: "Võ Ngọc Linh",
    schoolId: "school-erg-alpha",
    schoolName: "ERG Alpha Campus",
    classId: "class-6a1",
    className: "Lớp 6A1",
    gradeLabel: "Khối 6",
    avatarSeed: "NL",
    currentAssignment: "Ôn tập phân số và quy đồng",
    currentStage: "Đang làm câu 8/10",
    progressRate: 82,
    averageScore: 92,
    streakDays: 12,
    completedAssignments: 18,
    status: "ahead",
    mentorNote: "Tự học đều, phù hợp giao thêm câu hỏi stretch.",
    lastActivity: "3 phút trước",
  },
  {
    id: "student-minh-khoi",
    name: "Nguyễn Minh Khôi",
    schoolId: "school-erg-alpha",
    schoolName: "ERG Alpha Campus",
    classId: "class-6a1",
    className: "Lớp 6A1",
    gradeLabel: "Khối 6",
    avatarSeed: "MK",
    currentAssignment: "Reading sprint - daily routines",
    currentStage: "Hoàn thành, chờ giáo viên phản hồi",
    progressRate: 100,
    averageScore: 88,
    streakDays: 9,
    completedAssignments: 17,
    status: "steady",
    mentorNote: "Ổn định, cần tăng tốc ở câu hỏi suy luận.",
    lastActivity: "14 phút trước",
  },
  {
    id: "student-thao-my",
    name: "Trần Thảo My",
    schoolId: "school-erg-alpha",
    schoolName: "ERG Alpha Campus",
    classId: "class-6a1",
    className: "Lớp 6A1",
    gradeLabel: "Khối 6",
    avatarSeed: "TM",
    currentAssignment: "Ôn tập phân số và quy đồng",
    currentStage: "Đang làm câu 4/10",
    progressRate: 43,
    averageScore: 74,
    streakDays: 4,
    completedAssignments: 13,
    status: "support",
    mentorNote: "Hay bỏ trống câu vận dụng, nên giao nhắc nhở theo chặng.",
    lastActivity: "7 phút trước",
  },
  {
    id: "student-gia-han",
    name: "Lê Gia Hân",
    schoolId: "school-erg-alpha",
    schoolName: "ERG Alpha Campus",
    classId: "class-6a1",
    className: "Lớp 6A1",
    gradeLabel: "Khối 6",
    avatarSeed: "GH",
    currentAssignment: "An toàn số - tạo mật khẩu mạnh",
    currentStage: "Đang xem feedback",
    progressRate: 100,
    averageScore: 95,
    streakDays: 15,
    completedAssignments: 19,
    status: "ahead",
    mentorNote: "Top performer, phù hợp làm nhóm trưởng hỗ trợ bạn khác.",
    lastActivity: "9 phút trước",
  },
  {
    id: "student-quoc-bao",
    name: "Phạm Quốc Bảo",
    schoolId: "school-erg-alpha",
    schoolName: "ERG Alpha Campus",
    classId: "class-6a1",
    className: "Lớp 6A1",
    gradeLabel: "Khối 6",
    avatarSeed: "QB",
    currentAssignment: "Reading sprint - daily routines",
    currentStage: "Chưa mở bài",
    progressRate: 0,
    averageScore: 69,
    streakDays: 1,
    completedAssignments: 10,
    status: "support",
    mentorNote: "Cần gọi nhắc trực tiếp trước giờ tự học tối.",
    lastActivity: "1 giờ trước",
  },
  {
    id: "student-van-an",
    name: "Huỳnh Văn An",
    schoolId: "school-erg-alpha",
    schoolName: "ERG Alpha Campus",
    classId: "class-7b1",
    className: "Lớp 7B1",
    gradeLabel: "Khối 7",
    avatarSeed: "VA",
    currentAssignment: "Bảng tính - hàm SUM và AVERAGE",
    currentStage: "Đang làm câu 6/8",
    progressRate: 74,
    averageScore: 83,
    streakDays: 8,
    completedAssignments: 15,
    status: "steady",
    mentorNote: "Giữ nhịp tốt, nên đẩy thêm một bài challenge mỗi tuần.",
    lastActivity: "6 phút trước",
  },
  {
    id: "student-ngoc-tram",
    name: "Đặng Ngọc Trâm",
    schoolId: "school-erg-east",
    schoolName: "ERG East Learning Point",
    classId: "class-7c2",
    className: "Lớp 7C2",
    gradeLabel: "Khối 7",
    avatarSeed: "NT",
    currentAssignment: "Reading sprint - daily routines",
    currentStage: "Đang làm câu 5/10",
    progressRate: 57,
    averageScore: 76,
    streakDays: 5,
    completedAssignments: 12,
    status: "steady",
    mentorNote: "Cần thêm checkpoint giữa bài để giảm bỏ cuộc nửa chừng.",
    lastActivity: "11 phút trước",
  },
  {
    id: "student-khanh-duy",
    name: "Trần Khánh Duy",
    schoolId: "school-erg-east",
    schoolName: "ERG East Learning Point",
    classId: "class-8d1",
    className: "Lớp 8D1",
    gradeLabel: "Khối 8",
    avatarSeed: "KD",
    currentAssignment: "Vật lý - lực ma sát trong đời sống",
    currentStage: "Chờ nộp phần tự luận",
    progressRate: 88,
    averageScore: 81,
    streakDays: 7,
    completedAssignments: 14,
    status: "steady",
    mentorNote: "Phản hồi tự luận khá tốt, nên tăng độ sâu phần reasoning.",
    lastActivity: "18 phút trước",
  },
  {
    id: "student-thien-phuc",
    name: "Phan Thiện Phúc",
    schoolId: "school-erg-south",
    schoolName: "ERG South Studio",
    classId: "class-6m1",
    className: "Lớp 6M1",
    gradeLabel: "Khối 6",
    avatarSeed: "TP",
    currentAssignment: "An toàn số - tạo mật khẩu mạnh",
    currentStage: "Hoàn thành 100%",
    progressRate: 100,
    averageScore: 90,
    streakDays: 11,
    completedAssignments: 16,
    status: "ahead",
    mentorNote: "Có thể kéo vào nhóm thi đua cấp cụm.",
    lastActivity: "22 phút trước",
  },
];

const generated6A1Names = [
  "Nguyễn Bảo An",
  "Trần Minh Anh",
  "Lê Tuấn Anh",
  "Phạm Gia Bảo",
  "Hoàng Nhật Bảo",
  "Đỗ Ngọc Châu",
  "Vũ Minh Châu",
  "Bùi Khánh Chi",
  "Nguyễn Đức Duy",
  "Trần Hải Đăng",
  "Lê Minh Đức",
  "Phạm Thùy Dương",
  "Hoàng Gia Huy",
  "Đặng Tuấn Khang",
  "Nguyễn Khánh Linh",
  "Trần Bảo Long",
  "Lê Hoàng Minh",
  "Phạm Anh Minh",
  "Vũ Nhật Nam",
  "Bùi Hà My",
  "Nguyễn Yến Nhi",
  "Trần Minh Quân",
  "Lê Thanh Tâm",
  "Phạm Gia Tuệ",
  "Hoàng Minh Tuệ",
  "Đặng Phương Uyên",
  "Nguyễn Quốc Việt",
  "Trần Anh Vũ",
  "Lê Hải Yến",
  "Phạm Thiên Ân",
  "Vũ Bảo Ngọc",
  "Bùi Hoàng Phúc",
  "Nguyễn Nam Phong",
  "Trần Hà Vy",
  "Lê Quỳnh Anh",
  "Phạm Minh Khoa",
  "Hoàng Anh Thư",
  "Đặng Gia Hưng",
  "Nguyễn Hồng Nhung",
  "Trần Tuấn Kiệt",
  "Lê Phương Mai",
  "Phạm Bảo Trân",
  "Vũ Đức Anh",
  "Bùi Minh Triết",
  "Nguyễn Thiên Kim",
];

const generatedAssignmentPool = [
  {
    currentAssignment: "IC3 GS6 L1 - Thiết bị và hệ điều hành Train",
    stages: ["Chưa mở bài", "Đang làm checkpoint 1/3", "Đang làm checkpoint 2/3", "Hoàn thành, chờ phản hồi"],
  },
  {
    currentAssignment: "IC3 GS6 L1 - Internet an toàn Test",
    stages: ["Đang làm câu 4/12", "Đang làm câu 8/12", "Hoàn thành bài kiểm tra", "Cần xem lại câu sai"],
  },
  {
    currentAssignment: "IC3 GS6 L2 - Excel nhập môn Train",
    stages: ["Đang luyện thao tác bảng", "Đang làm checkpoint 2/4", "Hoàn thành bài luyện", "Chưa mở bài"],
  },
  {
    currentAssignment: "IC3 GS6 L2 - PowerPoint Test",
    stages: ["Đang làm câu 5/10", "Chờ nộp phần trình bày", "Hoàn thành, chờ chấm", "Cần bổ sung slide cuối"],
  },
  {
    currentAssignment: "IC3 GS6 L3 - Bảo mật tài khoản Train",
    stages: ["Đang đọc tình huống", "Đang làm checkpoint 3/5", "Hoàn thành 100%", "Cần xem lại mật khẩu mạnh"],
  },
];

function getAvatarSeed(name: string) {
  return name
    .split(" ")
    .filter(Boolean)
    .slice(-2)
    .map((part) => part[0])
    .join("")
    .toUpperCase();
}

function createGenerated6A1Students(): ClassroomStudent[] {
  const existing6A1Count = baseClassroomStudents.filter((student) => student.classId === "class-6a1").length;
  const neededCount = Math.max(0, 50 - existing6A1Count);

  return generated6A1Names.slice(0, neededCount).map((name, index) => {
    const assignment = generatedAssignmentPool[index % generatedAssignmentPool.length];
    const progressRate = [0, 18, 32, 45, 58, 67, 76, 84, 93, 100][index % 10];
    const status: StudentStatus = progressRate < 45 ? "support" : progressRate >= 84 ? "ahead" : "steady";

    return {
      id: `student-6a1-generated-${index + 1}`,
      name,
      schoolId: "school-erg-alpha",
      schoolName: "ERG Alpha Campus",
      classId: "class-6a1",
      className: "Lớp 6A1",
      gradeLabel: "Khối 6",
      avatarSeed: getAvatarSeed(name),
      currentAssignment: assignment.currentAssignment,
      currentStage: assignment.stages[index % assignment.stages.length],
      progressRate,
      averageScore: Math.min(98, 64 + ((index * 7) % 34)),
      streakDays: 1 + (index % 14),
      completedAssignments: 8 + (index % 13),
      status,
      mentorNote:
        status === "support"
          ? "Cần chia bài thành chặng ngắn và nhắc mở bài trong giờ tự học."
          : status === "ahead"
            ? "Có thể giao thêm bài nâng cao hoặc nhờ hỗ trợ bạn trong nhóm."
            : "Giữ nhịp ổn định, nên theo dõi thêm tốc độ hoàn thành trong tuần.",
      lastActivity: `${5 + index * 3} phút trước`,
    };
  });
}

export const classroomStudents: ClassroomStudent[] = [...baseClassroomStudents, ...createGenerated6A1Students()];

export const interventionQueue: InterventionItem[] = [
  {
    id: "intervention-1",
    schoolName: "ERG Alpha Campus",
    className: "Lớp 6A1",
    studentName: "Phạm Quốc Bảo",
    issue: "Chưa mở bài reading sprint dù đã quá 1 giờ từ lúc giao.",
    impact: "Nguy cơ rớt nhịp chuỗi bài trong tuần.",
    urgency: "high",
  },
  {
    id: "intervention-2",
    schoolName: "ERG East Learning Point",
    className: "Lớp 7C2",
    studentName: "Đặng Ngọc Trâm",
    issue: "Dừng ở giữa bài 3 phiên liên tiếp.",
    impact: "Tỷ lệ hoàn thành lớp giảm 4 điểm phần trăm.",
    urgency: "medium",
  },
  {
    id: "intervention-3",
    schoolName: "ERG East Learning Point",
    className: "Lớp 8D1",
    studentName: "Trần Khánh Duy",
    issue: "Tự luận tốt nhưng nộp trễ.",
    impact: "Chậm vòng review của giáo viên bộ môn.",
    urgency: "low",
  },
];

export const leaderboardByScope: Record<LeaderboardScope, LeaderboardEntry[]> = {
  class: [
    {
      id: "rank-class-1",
      name: "Lê Gia Hân",
      schoolName: "ERG Alpha Campus",
      className: "Lớp 6A1",
      score: 95,
      completionRate: 100,
      momentum: 12,
      badge: "Bứt tốc ổn định",
    },
    {
      id: "rank-class-2",
      name: "Võ Ngọc Linh",
      schoolName: "ERG Alpha Campus",
      className: "Lớp 6A1",
      score: 92,
      completionRate: 98,
      momentum: 9,
      badge: "Giữ phong độ",
    },
    {
      id: "rank-class-3",
      name: "Nguyễn Minh Khôi",
      schoolName: "ERG Alpha Campus",
      className: "Lớp 6A1",
      score: 88,
      completionRate: 96,
      momentum: 5,
      badge: "Tiến bộ đều",
    },
  ],
  grade: [
    {
      id: "rank-grade-1",
      name: "Lê Gia Hân",
      schoolName: "ERG Alpha Campus",
      className: "Lớp 6A1",
      score: 95,
      completionRate: 100,
      momentum: 12,
      badge: "Top khối 6",
    },
    {
      id: "rank-grade-2",
      name: "Phan Thiện Phúc",
      schoolName: "ERG South Studio",
      className: "Lớp 6M1",
      score: 90,
      completionRate: 99,
      momentum: 8,
      badge: "Bám đuổi tốt",
    },
    {
      id: "rank-grade-3",
      name: "Võ Ngọc Linh",
      schoolName: "ERG Alpha Campus",
      className: "Lớp 6A1",
      score: 92,
      completionRate: 98,
      momentum: 9,
      badge: "Ổn định cao",
    },
  ],
  school: [
    {
      id: "rank-school-1",
      name: "Lê Gia Hân",
      schoolName: "ERG Alpha Campus",
      className: "Lớp 6A1",
      score: 95,
      completionRate: 100,
      momentum: 12,
      badge: "Dẫn đầu trường",
    },
    {
      id: "rank-school-2",
      name: "Võ Ngọc Linh",
      schoolName: "ERG Alpha Campus",
      className: "Lớp 6A1",
      score: 92,
      completionRate: 98,
      momentum: 9,
      badge: "Cạnh tranh sát",
    },
    {
      id: "rank-school-3",
      name: "Huỳnh Văn An",
      schoolName: "ERG Alpha Campus",
      className: "Lớp 7B1",
      score: 83,
      completionRate: 91,
      momentum: 6,
      badge: "Top nâng cao",
    },
  ],
  cluster: [
    {
      id: "rank-cluster-1",
      name: "Lê Gia Hân",
      schoolName: "ERG Alpha Campus",
      className: "Lớp 6A1",
      score: 95,
      completionRate: 100,
      momentum: 12,
      badge: "Top cụm",
    },
    {
      id: "rank-cluster-2",
      name: "Phan Thiện Phúc",
      schoolName: "ERG South Studio",
      className: "Lớp 6M1",
      score: 90,
      completionRate: 99,
      momentum: 8,
      badge: "Đối trọng mạnh",
    },
    {
      id: "rank-cluster-3",
      name: "Võ Ngọc Linh",
      schoolName: "ERG Alpha Campus",
      className: "Lớp 6A1",
      score: 92,
      completionRate: 98,
      momentum: 9,
      badge: "Giữ nhịp cao",
    },
  ],
};

export const learnerJourneys: LearnerJourney[] = [
  {
    studentId: "student-ngoc-linh",
    strengths: [
      { label: "Nền tảng toán", value: 94 },
      { label: "Đọc hiểu", value: 88 },
      { label: "Kỷ luật nộp bài", value: 97 },
    ],
    focusAreas: ["Tăng độ sâu câu suy luận dài", "Giữ nhịp luyện tiếng Anh 3 buổi/tuần"],
    milestones: [
      { id: "m1", title: "Hoàn thành chuỗi phân số", detail: "4 bài liên tiếp trên 90 điểm.", state: "done" },
      { id: "m2", title: "Dẫn đầu lớp 6A1", detail: "Top 1 về điểm trung bình tuần.", state: "current" },
      { id: "m3", title: "Lên bảng thi đua cụm", detail: "Cần thêm 30 điểm thi đua.", state: "next" },
    ],
    mentorNote: "Nên giao vai trò peer mentor cho nhóm bạn cần củng cố nền tảng.",
  },
  {
    studentId: "student-thao-my",
    strengths: [
      { label: "Hoàn thành nhiệm vụ", value: 72 },
      { label: "Chính xác câu cơ bản", value: 79 },
      { label: "Kỷ luật học tập", value: 68 },
    ],
    focusAreas: ["Chia nhỏ bài tập thành checkpoint ngắn", "Tăng phản hồi sau mỗi 3 câu"],
    milestones: [
      { id: "m1", title: "Hoàn thành 2 bài liên tục", detail: "Đã đạt trong 4 ngày qua.", state: "done" },
      { id: "m2", title: "Ổn định trên 75%", detail: "Còn thiếu 1 bài để khóa mục tiêu.", state: "current" },
      { id: "m3", title: "Thoát danh sách cần hỗ trợ", detail: "Cần duy trì thêm 1 tuần.", state: "next" },
    ],
    mentorNote: "Phù hợp nhắc việc bằng mục tiêu nhỏ và phản hồi tích cực ngay sau khi nộp.",
  },
  {
    studentId: "student-gia-han",
    strengths: [
      { label: "Điểm trung bình", value: 97 },
      { label: "Tốc độ hoàn thành", value: 95 },
      { label: "Tính ổn định", value: 98 },
    ],
    focusAreas: ["Thử thách thêm bộ câu hỏi challenge", "Tham gia hỗ trợ nhóm đọc hiểu"],
    milestones: [
      { id: "m1", title: "Giữ top 1 lớp", detail: "3 tuần liên tiếp.", state: "done" },
      { id: "m2", title: "Top khối 6", detail: "Đang bám rất chắc.", state: "current" },
      { id: "m3", title: "Top cụm Trung tâm", detail: "Cần thêm một bài challenge.", state: "next" },
    ],
    mentorNote: "Nên trao huy hiệu leader để kéo động lực thi đua cho cả lớp.",
  },
];

export const defaultSchoolId = classroomSchools[0]?.id ?? "";
export const defaultClassId = classroomSnapshots[0]?.id ?? "";
export const defaultStudentId = classroomStudents[0]?.id ?? "";

export function getSchoolSnapshots(schoolId: string) {
  return classroomSnapshots.filter((snapshot) => snapshot.schoolId === schoolId);
}

export function getStudentsByClass(classId: string) {
  return classroomStudents.filter((student) => student.classId === classId);
}

export function getLeaderboard(scope: LeaderboardScope) {
  return leaderboardByScope[scope];
}

export function getLearnerJourney(studentId: string) {
  return learnerJourneys.find((journey) => journey.studentId === studentId) ?? learnerJourneys[0];
}
