import AssignmentTurnedInOutlinedIcon from "@mui/icons-material/AssignmentTurnedInOutlined";
import ForumOutlinedIcon from "@mui/icons-material/ForumOutlined";
import HomeOutlinedIcon from "@mui/icons-material/HomeOutlined";
import NotificationsNoneOutlinedIcon from "@mui/icons-material/NotificationsNoneOutlined";
import SchoolOutlinedIcon from "@mui/icons-material/SchoolOutlined";

import type { StudentAssignmentStatus } from "@/features/elearning/student-dashboard/types/student-dashboard-types";
import type { DashboardCopy } from "@/features/elearning/student-dashboard/types/dashboard-view-types";

export const viCopy: DashboardCopy = {
  navItems: [
    { key: "overview", label: "Tổng quan", icon: <HomeOutlinedIcon fontSize="small" /> },
    { key: "assignments", label: "Bài tập", icon: <AssignmentTurnedInOutlinedIcon fontSize="small" /> },
    { key: "scores", label: "Điểm bài tập", icon: <SchoolOutlinedIcon fontSize="small" /> },
    { key: "discussion", label: "Thảo luận", icon: <ForumOutlinedIcon fontSize="small" /> },
    { key: "announcements", label: "Thông báo", icon: <NotificationsNoneOutlinedIcon fontSize="small" /> },
  ],
  heroEyebrow: "Bảng học tập",
  heroTitle: (name: string) => `Chào ${name}, chọn bài cần làm hôm nay.`,
  heroDescription: (taskTitle: string) =>
    `Ưu tiên của bạn là "${taskTitle}". Màn hình này gom bài tập, tiến độ và điểm số vào từng trang rõ ràng để bạn không phải tìm lâu.`,
  primaryAction: "Làm bài ưu tiên",
  secondaryAction: "Xem bài tập",
  stats: {
    open: "Bài đang mở",
    overdue: "Bài quá hạn",
    average: "Điểm trung bình",
    completed: "Bài đã hoàn thành",
  },
  priority: {
    title: "Việc nên làm ngay",
    action: "Vào làm bài",
    detail: (dueLabel: string) => `Hạn: ${dueLabel}. Hoàn thành bài này trước để giữ nhịp học.`,
  },
  todayTitle: "Bài cần xử lý hôm nay",
  assignmentsTitle: "Bài tập",
  assignmentsDescription: "Tất cả bài được giao, trạng thái quá hạn, tiến độ hoàn thành và điểm số.",
  scoresTitle: "Điểm bài tập",
  scoresDescription: "Theo dõi điểm cao nhất và 3 kết quả gần đây của từng bài tập đã được giao.",
  bestScoreLabel: "Điểm cao nhất",
  recentResultsTitle: "Kết quả gần đây",
  noRecentResults: "Chưa có lần làm nào cho bài tập này.",
  attemptDurationLabel: "Thời gian làm bài",
  discussionTitle: "Thảo luận lớp",
  discussionDescription: "Hỏi bài và trao đổi với các bạn trong cùng lớp, giống diễn đàn lớp học.",
  discussionComposerTitle: "Đặt câu hỏi mới",
  discussionTitlePlaceholder: "Bạn đang vướng phần nào?",
  discussionBodyPlaceholder: "Viết rõ câu hỏi, cách bạn đã thử làm hoặc phần chưa hiểu...",
  discussionAttachmentAction: "Chèn ảnh",
  discussionAttachmentHint: "Có thể thêm nhiều ảnh minh họa.",
  discussionRemoveAttachment: "Bỏ ảnh",
  discussionModerationWarning: "Nội dung này có từ không phù hợp nên đã được hệ thống thay bằng ***.",
  discussionPostAction: "Đăng câu hỏi",
  discussionReplyPlaceholder: "Viết phản hồi cho chủ đề này...",
  discussionReplyAction: "Trả lời",
  discussionRepliesLabel: (count: number) => `${count} phản hồi`,
  discussionResolvedLabel: "Đã giải đáp",
  discussionRelatedLabel: "Bài liên quan",
  discussionEmptyTitle: "Chưa có thảo luận nào",
  discussionEmptyDescription: "Bạn có thể mở chủ đề đầu tiên để hỏi bài cùng lớp.",
  discussionPageLabel: (page: number, totalPages: number) => `Trang ${page}/${totalPages}`,
  discussionPreviousPage: "Trước",
  discussionNextPage: "Tiếp",
  announcementTitle: "Thông báo giáo viên",
  announcementDescription: "Tất cả thông báo từ giáo viên gửi riêng cho bạn hoặc gửi chung cho lớp.",
  announcementHeroTitle: "Chưa có thông báo mới",
  announcementHeroEmpty: "Khi giáo viên gửi thông báo, nội dung quan trọng sẽ hiển thị tại đây.",
  announcementPinnedLabel: "Quan trọng",
  announcementPopupAutoDismiss: "Tự tắt sau 30 giây",
  announcementPopupAction: "Xem chi tiết",
  announcementPopupDismiss: "Tắt thông báo",
  announcementPopupSnooze: "Không nhận thông báo này trong 2 giờ",
  notificationTitle: "Thông báo",
  notificationEmpty: "Chưa có thông báo mới.",
  notificationNewTopicLabel: "Chủ đề mới",
  notificationImageOnly: "Đã gửi ảnh",
  notificationNewThread: (authorName: string) => `${authorName} đã tạo chủ đề mới`,
  notificationNewReply: (authorName: string) => `${authorName} đã trả lời bạn`,
  notificationTopicContext: (title: string) => `trong "${title}"`,
  accountTitle: "Quản lý tài khoản",
  accountDescription: "Thông tin hồ sơ học sinh, trạng thái đăng nhập và các thao tác tài khoản.",
  learningProfileTitle: "Hồ sơ học tập",
  loginStateTitle: "Trạng thái đăng nhập",
  accountActionsTitle: "Thao tác tài khoản",
  progressLabel: "Tiến độ",
  questionCountLabel: "Câu đã làm",
  scoreLabel: "Điểm",
  scoreBadge: (score: number, maxScore: number) => `${score}/${maxScore}`,
  pendingScore: "Chờ chấm",
  assignmentAction: (status: StudentAssignmentStatus) =>
    status === "in_progress" ? "Làm tiếp" : status === "overdue" ? "Làm ngay" : status === "submitted" ? "Đã nộp" : "Bắt đầu",
  signedInAs: "Đã đăng nhập",
  guestLabel: "Chưa đăng nhập",
  signIn: "Đăng nhập",
  signOut: "Đăng xuất",
  footerTitle: "ERG Edurise Global",
  footerSubtitle: "Learn today, lead tomorrow",
  sessionBadge: "Quiz session",
  sessionEyebrow: "Phiên làm bài",
  sessionDescription: (subject: string, teacher: string, dueLabel: string) =>
    `${subject} • ${teacher} • ${dueLabel}. Hoàn thành trọn phiên để hệ thống cập nhật tiến độ và điểm số.`,
  backToDashboard: "Quay lại",
};

export const enCopy: DashboardCopy = {
  navItems: [
    { key: "overview", label: "Overview", icon: <HomeOutlinedIcon fontSize="small" /> },
    { key: "assignments", label: "Assignments", icon: <AssignmentTurnedInOutlinedIcon fontSize="small" /> },
    { key: "scores", label: "Assignment scores", icon: <SchoolOutlinedIcon fontSize="small" /> },
    { key: "discussion", label: "Discussion", icon: <ForumOutlinedIcon fontSize="small" /> },
    { key: "announcements", label: "Notices", icon: <NotificationsNoneOutlinedIcon fontSize="small" /> },
  ],
  heroEyebrow: "Learning board",
  heroTitle: (name: string) => `Hi ${name}, choose what to finish today.`,
  heroDescription: (taskTitle: string) =>
    `Your priority is "${taskTitle}". Assignments, progress, and scores are separated into clear pages so students can find the next action quickly.`,
  primaryAction: "Open priority task",
  secondaryAction: "View assignments",
  stats: {
    open: "Open tasks",
    overdue: "Overdue",
    average: "Average score",
    completed: "Completed tasks",
  },
  priority: {
    title: "Best next action",
    action: "Start task",
    detail: (dueLabel: string) => `Due: ${dueLabel}. Finish this first to keep your learning pace.`,
  },
  todayTitle: "Tasks to handle today",
  assignmentsTitle: "Assignments",
  assignmentsDescription: "All assigned tasks, overdue status, completion progress, and score.",
  scoresTitle: "Assignment scores",
  scoresDescription: "Review the best score and 3 most recent results for each assigned task.",
  bestScoreLabel: "Best score",
  recentResultsTitle: "Recent results",
  noRecentResults: "No attempts have been recorded for this assignment yet.",
  attemptDurationLabel: "Attempt time",
  discussionTitle: "Class discussion",
  discussionDescription: "Ask questions and exchange ideas with classmates, like a simple classroom forum.",
  discussionComposerTitle: "Start a new question",
  discussionTitlePlaceholder: "What part are you stuck on?",
  discussionBodyPlaceholder: "Write the question, what you tried, or the exact step you do not understand...",
  discussionAttachmentAction: "Add image",
  discussionAttachmentHint: "You can attach multiple reference images.",
  discussionRemoveAttachment: "Remove",
  discussionModerationWarning: "This message had inappropriate words and they were replaced with ***.",
  discussionPostAction: "Post question",
  discussionReplyPlaceholder: "Write a reply for this topic...",
  discussionReplyAction: "Reply",
  discussionRepliesLabel: (count: number) => `${count} replies`,
  discussionResolvedLabel: "Resolved",
  discussionRelatedLabel: "Related task",
  discussionEmptyTitle: "No discussions yet",
  discussionEmptyDescription: "Start the first topic to ask classmates for help.",
  discussionPageLabel: (page: number, totalPages: number) => `Page ${page}/${totalPages}`,
  discussionPreviousPage: "Previous",
  discussionNextPage: "Next",
  announcementTitle: "Teacher notices",
  announcementDescription: "All teacher notices sent directly to you or to your class.",
  announcementHeroTitle: "No new notices",
  announcementHeroEmpty: "Important teacher notices will appear here when they are posted.",
  announcementPinnedLabel: "Important",
  announcementPopupAutoDismiss: "Auto closes in 30 seconds",
  announcementPopupAction: "Open detail",
  announcementPopupDismiss: "Dismiss notice",
  announcementPopupSnooze: "Hide this notice for 2 hours",
  notificationTitle: "Notifications",
  notificationEmpty: "No new notifications.",
  notificationNewTopicLabel: "New topic",
  notificationImageOnly: "Sent an image",
  notificationNewThread: (authorName: string) => `${authorName} created a new topic`,
  notificationNewReply: (authorName: string) => `${authorName} replied to you`,
  notificationTopicContext: (title: string) => `in "${title}"`,
  accountTitle: "Manage account",
  accountDescription: "Student profile, login state, and account actions.",
  learningProfileTitle: "Learning profile",
  loginStateTitle: "Login state",
  accountActionsTitle: "Account actions",
  progressLabel: "Progress",
  questionCountLabel: "Questions",
  scoreLabel: "Score",
  scoreBadge: (score: number, maxScore: number) => `${score}/${maxScore}`,
  pendingScore: "Pending",
  assignmentAction: (status: StudentAssignmentStatus) =>
    status === "in_progress" ? "Continue" : status === "overdue" ? "Do now" : status === "submitted" ? "Submitted" : "Start",
  signedInAs: "Signed in",
  guestLabel: "Not signed in",
  signIn: "Sign in",
  signOut: "Sign out",
  footerTitle: "ERG Edurise Global",
  footerSubtitle: "Learn today, lead tomorrow",
  sessionBadge: "Quiz session",
  sessionEyebrow: "Quiz mode",
  sessionDescription: (subject: string, teacher: string, dueLabel: string) =>
    `${subject} • ${teacher} • ${dueLabel}. Finish the full session to refresh progress and score.`,
  backToDashboard: "Back",
};
